// =====================================================================
//  UMEH-3: closed over-ear module on a behind-the-ear hook.
//  One PETG shell for every 40-60 mm driver; no glue, no screws.
//
//  shell        PETG, one piece: flange plate for the round 110 mm pad + closed cup + hook boss + socket housing.
//  front_ring   PETG, 3-lug bayonet (30 deg turn by hand): locks adapter + driver from the front.
//  adapter(D)   TPU 95A, one per driver size: rim seat, aperture lip, conical spring flap (axial preload).
//  bushing      TPU 95A friction bushing in the boss: the hook wire turns and slides in it to set the height.
//  (rotation)   the wire tail is bent into a crank whose pin drops into one of 9 holes in lock_wall().
//  neckband     music wire in a silicone sleeve; its end snaps into a keyhole channel in the back of the cup
//               (the wire end bent into a blind hole), so nothing stands on the back face.
//  hook         music wire, PTFE liner, silicone sleeves (purchased, cut to length; wire bent on the jig).
//  pad          purchased round 110 mm velour pad (visual), front_foam: 3 mm reticulated PU disc.
//  Frame: x forward, y up, z away from the head; origin on the pad axis in the skin plane. Right side;
//  left = mirror([1,0,0]).  Numbers: params3.scad (generated by calc/umeh3/geom.py).
// =====================================================================
include <params3.scad>
part = "assembly";
pp = "";                 // placed part to export alone (head frame), e.g. -D part="none" -D pp="shell"
D = 50;
side = "R";
$fn = $preview ? 64 : 128;

function drv(d) = DRV[search(d, DRV)[0]];
R_HUB = POCKET_R + HUB_WALL;                 // shell outer radius around the pocket centre
ZL_ADP = RING_T;                             // adapter front face (local z from the plate face)
ZL_SH = RING_T + ADAPTER_H - ADAPTER_SQ;     // shoulder front face
ZL_CH = ZL_SH + SHOULDER_T;                  // chamber starts
AP_R = 52.8 / 2;                             // front ring opening (60 mm driver aperture)
LUG_A0 = [20, 140, 260];                     // lug entry angles (clear of the hook boss and the socket)
HOOK_ANG = atan2(HH[1] - PC[1], HH[0] - PC[0]);
SOCK_Z = 12.0;                               // socket housing centre, local z

module at_pc() { translate([PC[0], PC[1], Z_F]) children(); }

// ---------------------------------------------------------------- shell
module cup_outer2d() {      // (r, zl) about the pocket centre
    hull() {
        square([R_HUB, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - CUP_ROUND]) circle(r = CUP_ROUND, $fn = 64);
        square([0.01, CUP_H]);
    }
}
module cup_inner2d() {
    translate([0, ZL_CH]) hull() {
        square([R_HUB - WALL, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - ZL_CH - CUP_ROUND]) circle(r = CUP_ROUND - WALL, $fn = 64);
        square([0.01, CUP_H - ZL_CH - WALL]);
    }
    translate([0, -1]) square([POCKET_R, ZL_SH + 1]);          // pocket
    translate([0, -1]) square([SHOULDER_RI, ZL_CH + 2]);       // through the shoulder
}
module flange() {
    translate([0, 0, Z_F]) difference() {
        union() {
            cylinder(d = FLANGE_OD, h = PLATE_T);
            // rear bead on the rim: the pad's elastic lip hooks behind it
            rotate_extrude($fn = 160) translate([FLANGE_OD / 2 - BEAD_R, PLATE_T + BEAD_R * 0.6]) circle(r = BEAD_R, $fn = 24);
            translate([0, 0, PLATE_T - 0.01]) difference() {
                cylinder(d = FLANGE_OD - 0.4, h = BEAD_R * 0.6 + 0.01);
                translate([0, 0, -1]) cylinder(d = FLANGE_OD - 2 * BEAD_R - 1.6, h = 5);
            }
        }
        // front edge chamfer (the pad lip slides on)
        translate([0, 0, -0.01]) difference() { cylinder(d = FLANGE_OD + 1, h = 0.6); cylinder(d1 = FLANGE_OD - 1.2, d2 = FLANGE_OD + 0.01, h = 0.6); }
    }
}
// rotation lock: arc wall on the back of the plate around the hook boss axis, away from the cup, with a row of holes
// for the pin at the end of the wire crank. LOCK = [r, w, hole, depth, step, n]
module lock_wall() {
    a_out = atan2(HH[1] - PC[1], HH[0] - PC[0]);
    span = (LOCK[5] - 1) * LOCK[4] + 2 * LOCK[1] / LOCK[0] * 180 / PI;
    translate([HH[0], HH[1], Z_F + PLATE_T - 0.01]) difference() {
        rotate([0, 0, a_out - span / 2]) rotate_extrude(angle = span, $fn = 160)
            translate([LOCK[0] - LOCK[1] / 2, 0]) intersection() { offset(r = 1.0) offset(delta = -1.0) translate([0, -2]) square([LOCK[1], BOSS_L - PLATE_T + 2]); square([LOCK[1], BOSS_L]); }
        for (k = [0 : LOCK[5] - 1]) rotate([0, 0, a_out + (k - (LOCK[5] - 1) / 2) * LOCK[4]])
            translate([LOCK[0], 0, BOSS_L - PLATE_T - LOCK[3]]) cylinder(d = LOCK[2], h = LOCK[3] + 1, $fn = 20);
    }
}
module hook_boss_solid() {
    hull() {
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 0.8, $fn = 48);
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 0.8, h = BOSS_L, $fn = 48);
        at_pc() rotate([0, 0, HOOK_ANG]) translate([R_HUB - 2.5, 0, 0]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 3, $fn = 48);
    }
}
module socket_housing(cut = false) {
    // 2-pin 0.78 mm female socket, opening facing down-rear; the cable leaves low and backwards
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0]) rotate([0, 0, 0])
        if (!cut) hull() for (i = [-1, 1], j = [-1, 1]) {
            // rounded box (r 2) that grows out of the cup wall, outer end domed
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, -3]) cylinder(r = 2, h = SOCKET[1] + 1.2, $fn = 24);
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, SOCKET[1] - 1.8]) sphere(r = 2, $fn = 24);
        }
        else {
            translate([-(SOCKET[2] + 0.3) / 2, -(SOCKET[0] + 0.3) / 2, -0.5]) cube([SOCKET[2] + 0.3, SOCKET[0] + 0.3, SOCKET[1] + 5]);
            translate([0, 0, -6]) cylinder(d = 3.0, h = 7, $fn = 24);             // lead hole into the chamber
        }
}
// small pad: the wire passes the plate under the pad and runs in a groove in the plate face to the pad opening
module groove_path(w, z0, h) {
    hull() for (r = [GROOVE_R_IN - 1.5, norm(HH)]) rotate([0, 0, HOOK_A]) translate([r, 0, z0]) cylinder(d = w, h = h, $fn = 24);
}
module groove_rib() { groove_path(WIRE_D + 3.2, Z_F, PLATE_T + 1.6); }
module groove_cut() { groove_path(WIRE_D + 0.4, Z_F - 1, 1 + 0.3 + WIRE_D / 2 + 0.2); }
module bayonet_cut() {
    for (a = LUG_A0) {
        // axial entry channel
        rotate([0, 0, a]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, -1]) square([LUG_DEPTH + 0.1, RING_T + 1.01]);
        // circumferential groove under the retaining lip
        rotate([0, 0, a]) rotate_extrude(angle = TWIST + LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, RING_T - LUG_H - 0.15]) square([LUG_DEPTH + 0.1, LUG_H + 0.15 + 0.01]);
    }
}
// band channel in the back: a trough (spine) inside the back carries the sleeve; keyhole profile (axis 1.2 mm under
// the surface: 3.6 mm opening on the 4 mm sleeve, it snaps in); blind hole for the bent wire end
module neck_spine() {
    if (NECK != undef) intersection() {
        union() { sweep_tube(NECK, NECK_SL + 0.3 + 2 * WALL, 1, NECK_EMB); translate(NECK[1] - [0, 0, NECK_PIN / 2]) sphere(d = 7, $fn = 32); }
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
}
module neck_channel() {
    if (NECK != undef) {
        sweep_tube(NECK, NECK_SL + 0.3, 1, NECK_EMB);
        // let the sleeve leave the channel along its exit direction
        hull() { translate(NECK[NECK_EMB]) sphere(d = NECK_SL + 0.3, $fn = 20); translate(NECK[NECK_EMB + 1]) sphere(d = NECK_SL + 0.3, $fn = 20); }
        translate(NECK[0]) cylinder(d = NECK_D + 0.25, h = NECK[1][2] - NECK[0][2] + 1, $fn = 20);
    }
}
// ---------------------------------------------------------------- brand (commercial finish)
// Raised 0.4 mm wordmark on the flat back + a small side letter; printed in bronze by a filament change at the layer
// where the letters start (the back is the top of the print). A 0.4 mm groove ring frames the back face.
LOGO_TXT = "UMEH";
LOGO_FONT = "DejaVu Sans:style=Bold";
LOGO_H = 0.4;
logo_in_shell = true;                        // false: the viewer draws the letters as their own (bronze) part
module logo(letter, flip) {
    module flat2d() {
        translate([PC[0], PC[1] - 14.5]) text(LOGO_TXT, size = 5.0, font = LOGO_FONT, halign = "center", valign = "center", spacing = 1.22);
        translate([PC[0], PC[1] + 13.5]) text(letter, size = 3.2, font = LOGO_FONT, halign = "center", valign = "center");
    }
    translate([0, 0, Z_F + CUP_H - 0.01]) linear_extrude(LOGO_H + 0.01)
        if (flip) translate([PC[0], 0]) mirror([1, 0]) translate([-PC[0], 0]) flat2d(); else flat2d();
}
module bezel_groove() {
    at_pc() translate([0, 0, CUP_H - 0.4]) difference() { cylinder(r = 22.6, h = 1, $fn = 160); translate([0, 0, -1]) cylinder(r = 21.8, h = 3, $fn = 160); }
}
// concave fillet where the cup meets the flange plate
module cup_fillet() {
    at_pc() rotate_extrude($fn = 160) translate([R_HUB - 0.01, PLATE_T - 0.01]) difference() { square([3, 3]); translate([3, 3]) circle(r = 3, $fn = 32); }
}
module shell() {
    if (logo_in_shell) logo(side, side == "L");
    shell_body();
}
module shell_body() {
    difference() {
        union() {
        difference() {
        union() {
            flange();
            at_pc() rotate_extrude($fn = 160) difference() { cup_outer2d(); }
            cup_fillet();
            hook_boss_solid();
            lock_wall();
            socket_housing(false);
            if (GROOVE) groove_rib();
        }
        at_pc() rotate_extrude($fn = 160) cup_inner2d();
        at_pc() bayonet_cut();
        // hook: wire passage through plate and boss, bushing bore at the back
        translate([HH[0], HH[1], Z_F - 1]) cylinder(d = WIRE_D + 0.3, h = BOSS_L + 2, $fn = 24);
        translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) cylinder(d = BUSH_OD, h = BUSH_L + 1, $fn = 48);
        socket_housing(true);
        if (GROOVE) groove_cut();
        // pocket front chamfer
        at_pc() translate([0, 0, -0.01]) cylinder(r1 = POCKET_R + 0.5, r2 = POCKET_R, h = 0.5);
    }
        neck_spine();
        }
        neck_channel();
        bezel_groove();
    }
}

// ---------------------------------------------------------------- front ring
module front_ring() {
    difference() {
        union() {
            cylinder(r = POCKET_R - 0.15, h = RING_T);
            for (a = LUG_A0) rotate([0, 0, a + 1]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180), $fn = 160)
                translate([POCKET_R - 0.5, RING_T - LUG_H]) square([LUG_DEPTH + 0.35, LUG_H - 0.15]);
        }
        translate([0, 0, -1]) cylinder(r = AP_R, h = RING_T + 2);
        translate([0, 0, -0.01]) cylinder(r1 = AP_R + 1.0, r2 = AP_R, h = 1.0);
        // two finger notches on the face (turn by hand)
        for (s = [0, 180]) rotate([0, 0, 80 + s]) translate([(AP_R + POCKET_R) / 2, 0, -0.01]) cylinder(d = 3.2, h = 1.0, $fn = 24);
    }
}

// ---------------------------------------------------------------- TPU adapter per driver
// front lip (aperture 0.88 D) with a conical spring flap at its outer edge; rim seat; back lip.
module adapter(d) {
    v = drv(d); ro = v[1] / 2; rt = v[2]; ap = v[5] / 2;
    RO = POCKET_R - 0.15;
    difference() {
        union() {
            translate([0, 0, 1.0]) cylinder(r = RO, h = ADAPTER_H - 1.0);       // body
            // conical spring flap: 0.8 mm TPU, stands 1.0 mm proud of the body front, flattened by the ring
            difference() {
                translate([0, 0, 0]) cylinder(r1 = RO - 3.0, r2 = RO, h = 1.01);
                translate([0, 0, -0.01]) cylinder(r1 = RO - 3.8, r2 = RO - 0.8, h = 1.03);
            }
            translate([0, 0, 0.6]) cylinder(r = max(ap + 1.5, ro - 1.2), h = 0.41);  // lip ring behind the flap
        }
        translate([0, 0, -1]) cylinder(r = ap, h = 10);                           // aperture
        translate([0, 0, 1.0]) cylinder(r = ro + 0.05, h = rt + 0.01);            // rim seat (driver snaps in)
        translate([0, 0, 1.0 + rt - 0.01]) cylinder(r = v[3] / 2 + 0.6, h = 10);   // back lip opening (basket)
        rotate([0, 0, SOCKET_A - 0]) translate([ro - 2, -1.2, 1.0]) cube([POCKET_R, 2.4, 10]);   // lead notch
    }
}

// ---------------------------------------------------------------- hook
module sweep_tube(pts, d, i0, i1) {
    for (i = [i0 : i1 - 1]) hull() { translate(pts[i]) sphere(d = d, $fn = 20); translate(pts[i + 1]) sphere(d = d, $fn = 20); }
}
module hook_wire() { sweep_tube(HOOK, WIRE_D, 0, len(HOOK) - 1); }
module sleeve_arch() { sweep_tube(HOOK, SIL_ARCH[1], HOOK_ARCH[0], HOOK_ARCH[1]); }
module sleeve_leg() {
    sweep_tube(HOOK, SIL_LEG[1], HOOK_DESC, HOOK_ARCH[0]);
    sweep_tube(HOOK, SIL_LEG[1], HOOK_ARCH[1], len(HOOK) - 1);
    translate(HOOK[len(HOOK) - 1]) sphere(d = SIL_LEG[1] + 1.5, $fn = 24);     // silicone end cap
}
// wide TPU paddle on the rear leg (bears on the back of the pinna; spreads the clamp force)
module paddle() {
    if (PADDLE != undef) {
        w = PADDLE[0]; L = PADDLE[1]; t = PADDLE[2];
        a = atan2(LEG_DIR[1], LEG_DIR[0]);
        difference() {
            translate([PINNA_PT[0], PINNA_PT[1], PINNA_PT[2] - t / 2]) rotate([0, 0, a]) hull()
                for (s = [-1, 1]) translate([s * (L - w) / 2, 0, 0]) cylinder(d = w, h = t, $fn = 40);
            sweep_tube(HOOK, WIRE_D + 0.1, HOOK_ARCH[1], len(HOOK) - 1);
        }
    }
}
// neckband: music wire in a silicone sleeve (first part; the rest runs around the nape) + PETG eye clip on the cup
module neckband() { if (NECK != undef) { sweep_tube(NECK, NECK_SL, 1, len(NECK) - 1); sweep_tube(NECK, NECK_D, 0, 1); } }
// wide soft saddle on the arch (model A final): TPU carrier clipped on the wire + slow-rebound foam strip in a velour sock
module saddle_sector(r0, r1) {
    translate([ARCH_C[0], ARCH_C[1], 0]) rotate([0, 0, ARCH_A[0]])
        rotate_extrude(angle = ARCH_A[1] - ARCH_A[0], $fn = 160)
            translate([r0, Z_ROOT - SADDLE[0] / 2]) offset(r = 0.8) offset(delta = -0.8) square([r1 - r0, SADDLE[0]]);
}
module saddle_foam() { if (SADDLE != undef) { rc = ARCH_R - 2 - SADDLE[2] - SADDLE[1]; saddle_sector(rc, rc + SADDLE[1]); } }
// carrier: thin TPU plate under the foam + a snap-on clip tube around the PTFE-lined wire (light: ~2 g)
module saddle_carrier() {
    if (SADDLE != undef) difference() {
        union() {
            saddle_sector(ARCH_R - 2 - SADDLE[2], ARCH_R - 0.6);
            sweep_tube(HOOK, PTFE[1] + 2.4, HOOK_ARCH[0], HOOK_ARCH[1]);
        }
        sweep_tube(HOOK, PTFE[1] + 0.2, HOOK_ARCH[0], HOOK_ARCH[1]);
    }
}
module bushing() {
    difference() { cylinder(d = BUSH_OD - 0.1, h = BUSH_L); translate([0, 0, -1]) cylinder(d = WIRE_D - 0.15, h = BUSH_L + 2, $fn = 24);
        translate([0, 0, BUSH_L - 1.0]) cylinder(d1 = WIRE_D - 0.15, d2 = WIRE_D + 0.8, h = 1.01, $fn = 24); }
}

// ---------------------------------------------------------------- purchased parts (visual / mass)
module pad() {
    t = PAD_T - PAD_COMP;
    rotate_extrude($fn = 160) hull() {
        translate([PAD_ID / 2 + 4, 4]) circle(r = 4, $fn = 32);
        translate([PAD_OD / 2 - 6, 6]) circle(r = 6, $fn = 32);
        translate([PAD_ID / 2 + 1, t - 1]) square([PAD_OD / 2 - PAD_ID / 2 - 1, 1]);
    }
    // fabric lip wrapped over the flange rim
    translate([0, 0, Z_F - 0.01]) difference() { cylinder(d = FLANGE_OD + 1.6, h = PLATE_T + 2.2); translate([0, 0, -1]) cylinder(d = FLANGE_OD - 6, h = 6); }
}
module front_foam() {
    translate([0, 0, Z_F - 3.0]) difference() {
        cylinder(d = PAD_ID + 4, h = 3.0);
        translate([HH[0], HH[1], -1]) cylinder(d = WIRE_D + 1, h = 5, $fn = 16);
    }
}
module driver_vis(d) {
    v = drv(d);
    difference() { cylinder(r = v[1] / 2, h = v[2]); translate([0, 0, -1]) cylinder(r = v[5] / 2 - 0.5, h = 5); }
    translate([0, 0, 0.3]) difference() { cylinder(r1 = v[5] / 2 - 0.5, r2 = v[3] * 0.18, h = v[4] * 0.25);
        translate([0, 0, -0.01]) cylinder(r1 = v[5] / 2 - 1.1, r2 = v[3] * 0.18 - 0.6, h = v[4] * 0.25 - 0.5); }
    translate([0, 0, v[2]]) cylinder(r1 = v[1] / 2 - 1.5, r2 = v[3] / 2, h = v[4] * 0.5);
    translate([0, 0, v[2] + v[4] * 0.5]) cylinder(r = v[3] / 2 * 0.85, h = v[4] * 0.5 - v[2]);
}
module socket_vis() {
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0])
        translate([-SOCKET[2] / 2, -SOCKET[0] / 2, 0]) cube([SOCKET[2], SOCKET[0], SOCKET[1]]);
}
module fibre() {
    at_pc() translate([0, 0, CUP_H - WALL - FIBRE_T]) cylinder(r = R_HUB - CUP_ROUND, h = FIBRE_T);
}

// ---------------------------------------------------------------- placed parts (head frame)
module placed(p) {
    if (p == "shell") shell();
    if (p == "front_ring") at_pc() translate([0, 0, 0]) front_ring();
    if (p == "adapter") at_pc() translate([0, 0, ZL_ADP]) adapter(D);
    if (p == "driver") at_pc() translate([0, 0, ZL_ADP + 1.0 - 0.0]) driver_vis(D);
    if (p == "bushing") translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) bushing();
    if (p == "wire") hook_wire();
    if (p == "sleeve_arch" && SADDLE == undef) sleeve_arch();
    if (p == "saddle_carrier") saddle_carrier();
    if (p == "saddle_foam") saddle_foam();
    if (p == "sleeve_leg") sleeve_leg();
    if (p == "pad") pad();
    if (p == "front_foam") front_foam();
    if (p == "socket") socket_vis();
    if (p == "paddle") paddle();
    if (p == "neckband") neckband();
    if (p == "fibre") fibre();
    if (p == "logo") logo(side, side == "L");
    if (p == "logo_L") logo("L", true);       // the left letters as the right side's mirror image (viewer)
}
PARTS = ["shell", "front_ring", "adapter", "driver", "bushing", "wire", "sleeve_arch", "sleeve_leg",
         "pad", "front_foam", "socket", "fibre", "paddle", "neckband", "saddle_carrier", "saddle_foam"];
COL = ["#2B2E33", "#A27449", "#1D1F22", "DimGray", "#1D1F22", "Silver", "#3A3D42", "#3A3D42",
       "#2E3036", "#55585E", "Goldenrod", "#8E8A80", "#1D1F22", "#3A3D42", "#1D1F22", "#2E3036"];

module sided() { if (side == "L") mirror([1, 0, 0]) children(); else children(); }

if (part == "assembly") sided() for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
if (part == "section") sided() difference() {
    for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
    translate([-100, -200 + PC[1], -10]) cube([200, 200, 100]);
}
if (pp != "") sided() placed(pp);
// print orientations
if (part == "print_shell") sided() translate([0, 0, -Z_F]) shell();
if (part == "print_front_ring") sided() front_ring();
if (part == "print_adapter") adapter(D);
if (part == "print_bushing") bushing();
if (part == "print_bend_jig") sided() bend_jig();

// wire bending jig (PETG plate with the hook path as a groove; bend the wire around the pins by hand)
module bend_jig() {
    difference() {
        translate([-34, -28, 0]) cube([62, 60, 4]);
        for (i = [HOOK_PLATE + 1 : len(HOOK) - 2]) hull() {
            translate([HOOK[i][0], HOOK[i][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
            translate([HOOK[i + 1][0], HOOK[i + 1][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
        }
    }
}
