// =====================================================================
//  UMEH-3: closed over-ear module on a behind-the-ear hook.
//  One PETG shell for every 40-60 mm driver; no glue, no screws.
//
//  shell        PETG, one piece: flange plate for the round 110 mm pad + closed cup + hook boss + socket housing.
//  front_ring   PETG, 3-lug bayonet (30 deg turn by hand): locks adapter + driver from the front.
//  adapter(D)   TPU 95A, one per driver size: rim seat, aperture lip, conical spring flap (axial preload).
//  bushing      TPU 95A friction bushing in the boss: the hook wire turns and slides in it to set the height.
//  (rotation)   the wire tail is bent into a crank whose pin drops into one of 9 holes in lock_wall().
//  neckband     music wire in a silicone sleeve; its end snaps into a keyhole channel in the back of the cup
//               (the wire end bent into a blind hole), so nothing stands on the back face.
//  hook         music wire, PTFE liner, silicone sleeves (purchased, cut to length; wire bent on the jig).
//  pad          purchased round 110 mm velour pad (visual), front_foam: 3 mm reticulated PU disc.
//  Frame: x forward, y up, z away from the head; origin on the pad axis in the skin plane. Right side;
//  left = mirror([1,0,0]).  Numbers: params3.scad (generated by calc/umeh3/geom.py).
// =====================================================================
include <params3.scad>
part = "assembly";
pp = "";                 // placed part to export alone (head frame), e.g. -D part="none" -D pp="shell"
D = 50;
side = "R";
$fn = $preview ? 64 : 128;

// waterproof build (UMEH-3W): defaults when WP is off; umeh3w.scad includes params3w.scad after this file
MEMB_T = 0; OR_CORD = 1.5; OR_G = [28, 30]; OR_GD = 1.2; CABLE_D = 2.2; GL_CORD = 1.0; GL_ID = 2.0;
POGO = [8.5, 7, 250, 19]; SLIDER = [11, -4, 12]; MAGNET = [6, 2]; MOD_SIDE = "R";
BOARD = [23, 16.5, 3]; CHARGER = [17, 26, 4]; BATT = [30, 20, 4]; POST_R = 24; POST_L = 5.3;

function drv(d) = DRV[search(d, DRV)[0]];
R_HUB = POCKET_R + HUB_WALL;                 // shell outer radius around the pocket centre
ZL_ADP = RING_T + MEMB_T;                    // adapter front face (local z from the plate face)
ZL_SH = RING_T + MEMB_T + ADAPTER_H - ADAPTER_SQ;     // shoulder front face
ZL_CH = ZL_SH + SHOULDER_T;                  // chamber starts
AP_R = 52.8 / 2;                             // front ring opening (60 mm driver aperture)
// lug entry angles (clear of the hook boss and the socket); the waterproof pocket is 1.2 mm wider, its grooves would
// reach the hook wire hole at 49 deg, so the lugs turn to put the hook in the middle of a gap
LUG_A0 = WP == true ? [80, 200, 320] : [20, 140, 260];
HOOK_ANG = atan2(HH[1] - PC[1], HH[0] - PC[0]);
SOCK_Z = 12.0;                               // socket housing centre, local z

module at_pc() { translate([PC[0], PC[1], Z_F]) children(); }

// ---------------------------------------------------------------- shell
module cup_outer2d() {      // (r, zl) about the pocket centre
    hull() {
        square([R_HUB, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - CUP_ROUND]) circle(r = CUP_ROUND, $fn = 64);
        square([0.01, CUP_H]);
    }
}
module cup_inner2d() {
    translate([0, ZL_CH]) hull() {
        square([R_HUB - WALL, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - ZL_CH - CUP_ROUND]) circle(r = CUP_ROUND - WALL, $fn = 64);
        square([0.01, CUP_H - ZL_CH - WALL]);
    }
    translate([0, -1]) square([POCKET_R, ZL_SH + 1]);          // pocket
    translate([0, -1]) square([SHOULDER_RI, ZL_CH + 2]);       // through the shoulder
}
module flange() {
    translate([0, 0, Z_F]) difference() {
        union() {
            cylinder(d = FLANGE_OD, h = PLATE_T);
            // rear bead on the rim: the pad's elastic lip hooks behind it
            rotate_extrude($fn = 160) translate([FLANGE_OD / 2 - BEAD_R, PLATE_T + BEAD_R * 0.6]) circle(r = BEAD_R, $fn = 24);
            translate([0, 0, PLATE_T - 0.01]) difference() {
                cylinder(d = FLANGE_OD - 0.4, h = BEAD_R * 0.6 + 0.01);
                translate([0, 0, -1]) cylinder(d = FLANGE_OD - 2 * BEAD_R - 1.6, h = 5);
            }
        }
        // front edge chamfer (the pad lip slides on)
        translate([0, 0, -0.01]) difference() { cylinder(d = FLANGE_OD + 1, h = 0.6); cylinder(d1 = FLANGE_OD - 1.2, d2 = FLANGE_OD + 0.01, h = 0.6); }
    }
}
// rotation lock: arc wall on the back of the plate around the hook boss axis, away from the cup, with a row of holes
// for the pin at the end of the wire crank. LOCK = [r, w, hole, depth, step, n]
module lock_wall() {
    a_out = atan2(HH[1] - PC[1], HH[0] - PC[0]);
    span = (LOCK[5] - 1) * LOCK[4] + 2 * LOCK[1] / LOCK[0] * 180 / PI;
    translate([HH[0], HH[1], Z_F + PLATE_T - 0.01]) difference() {
        rotate([0, 0, a_out - span / 2]) rotate_extrude(angle = span, $fn = 160)
            translate([LOCK[0] - LOCK[1] / 2, 0]) intersection() { offset(r = 1.0) offset(delta = -1.0) translate([0, -2]) square([LOCK[1], BOSS_L - PLATE_T + 2]); square([LOCK[1], BOSS_L]); }
        for (k = [0 : LOCK[5] - 1]) rotate([0, 0, a_out + (k - (LOCK[5] - 1) / 2) * LOCK[4]])
            translate([LOCK[0], 0, BOSS_L - PLATE_T - LOCK[3]]) cylinder(d = LOCK[2], h = LOCK[3] + 1, $fn = 20);
    }
}
module hook_boss_solid() {
    hull() {
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 0.8, $fn = 48);
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 0.8, h = BOSS_L, $fn = 48);
        at_pc() rotate([0, 0, HOOK_ANG]) translate([R_HUB - 2.5, 0, 0]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 3, $fn = 48);
    }
}
module socket_housing(cut = false) {
    // 2-pin 0.78 mm female socket, opening facing down-rear; the cable leaves low and backwards
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0]) rotate([0, 0, 0])
        if (!cut) hull() for (i = [-1, 1], j = [-1, 1]) {
            // rounded box (r 2) that grows out of the cup wall, outer end domed
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, -3]) cylinder(r = 2, h = SOCKET[1] + 1.2, $fn = 24);
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, SOCKET[1] - 1.8]) sphere(r = 2, $fn = 24);
        }
        else {
            translate([-(SOCKET[2] + 0.3) / 2, -(SOCKET[0] + 0.3) / 2, -0.5]) cube([SOCKET[2] + 0.3, SOCKET[0] + 0.3, SOCKET[1] + 5]);
            translate([0, 0, -6]) cylinder(d = 3.0, h = 7, $fn = 24);             // lead hole into the chamber
        }
}
// small pad: the wire passes the plate under the pad and runs in a groove in the plate face to the pad opening
module groove_path(w, z0, h) {
    hull() for (r = [GROOVE_R_IN - 1.5, norm(HH)]) rotate([0, 0, HOOK_A]) translate([r, 0, z0]) cylinder(d = w, h = h, $fn = 24);
}
module groove_rib() { groove_path(WIRE_D + 3.2, Z_F, PLATE_T + 1.6); }
module groove_cut() { groove_path(WIRE_D + 0.4, Z_F - 1, 1 + 0.3 + WIRE_D / 2 + 0.2); }
module bayonet_cut() {
    for (a = LUG_A0) {
        // axial entry channel
        rotate([0, 0, a]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, -1]) square([LUG_DEPTH + 0.1, RING_T + 1.01]);
        // circumferential groove under the retaining lip
        rotate([0, 0, a]) rotate_extrude(angle = TWIST + LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, RING_T - LUG_H - 0.15]) square([LUG_DEPTH + 0.1, LUG_H + 0.15 + 0.01]);
    }
}
// band channel in the back: a trough (spine) inside the back carries the sleeve; keyhole profile (axis 1.2 mm under
// the surface: 3.6 mm opening on the 4 mm sleeve, it snaps in); blind hole for the bent wire end
module neck_spine() {
    if (NECK != undef) intersection() {
        union() { sweep_tube(NECK, NECK_SL + 0.3 + 2 * WALL, 1, NECK_EMB); translate(NECK[1] - [0, 0, NECK_PIN / 2]) sphere(d = 7, $fn = 32); }
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
}
module neck_channel() {
    if (NECK != undef) {
        sweep_tube(NECK, NECK_SL + 0.3, 1, NECK_EMB);
        // let the sleeve leave the channel along its exit direction
        hull() { translate(NECK[NECK_EMB]) sphere(d = NECK_SL + 0.3, $fn = 20); translate(NECK[NECK_EMB + 1]) sphere(d = NECK_SL + 0.3, $fn = 20); }
        translate(NECK[0]) cylinder(d = NECK_D + 0.25, h = NECK[1][2] - NECK[0][2] + 1, $fn = 20);
    }
}
// ---------------------------------------------------------------- brand (commercial finish)
// Raised 0.4 mm wordmark on the flat back + a small side letter; printed in bronze by a filament change at the layer
// where the letters start (the back is the top of the print). A raised 0.8 mm ring in the same colour frames the back.
LOGO_TXT = "UMEH";
LOGO_FONT = "DejaVu Sans:style=Bold";
LOGO_H = 0.4;
logo_in_shell = true;                        // false: the viewer draws the letters as their own (bronze) part
module logo(letter, flip) {
    module flat2d() {
        translate([PC[0], PC[1] - 14.5]) text(LOGO_TXT, size = 5.0, font = LOGO_FONT, halign = "center", valign = "center", spacing = 1.22);
        translate([PC[0], PC[1] + 13.5]) text(letter, size = 3.2, font = LOGO_FONT, halign = "center", valign = "center");
        // accent ring framing the back face (same colour as the letters)
        translate([PC[0], PC[1]]) difference() { circle(r = 22.6, $fn = 160); circle(r = 21.8, $fn = 160); }
    }
    translate([0, 0, Z_F + CUP_H - 0.01]) linear_extrude(LOGO_H + 0.01)
        if (flip) translate([PC[0], 0]) mirror([1, 0]) translate([-PC[0], 0]) flat2d(); else flat2d();
}
module bezel_groove() {
    at_pc() translate([0, 0, CUP_H - 0.4]) difference() { cylinder(r = 22.6, h = 1, $fn = 160); translate([0, 0, -1]) cylinder(r = 21.8, h = 3, $fn = 160); }
}
// concave fillet where the cup meets the flange plate
module cup_fillet() {
    at_pc() rotate_extrude($fn = 160) translate([R_HUB - 0.01, PLATE_T - 0.01]) difference() { square([3, 3]); translate([3, 3]) circle(r = 3, $fn = 32); }
}
module shell() {
    if (logo_in_shell) logo(side, side == "L");
    shell_body();
}
module shell_body() {
    difference() {
        union() {
        difference() {
        union() {
            flange();
            at_pc() rotate_extrude($fn = 160) difference() { cup_outer2d(); }
            cup_fillet();
            hook_boss_solid();
            lock_wall();
            if (WP != true) socket_housing(false);
            if (GROOVE) groove_rib();
        }
        at_pc() rotate_extrude($fn = 160) cup_inner2d();
        at_pc() bayonet_cut();
        if (GROOVE) groove_cut();
        // pocket front chamfer
        at_pc() translate([0, 0, -0.01]) cylinder(r1 = POCKET_R + 0.5, r2 = POCKET_R, h = 0.5);
    }
        neck_spine();
        bushing_wall();
        if (WP == true) wp_solids();
        }
        neck_channel();
        // hook: wire passage through plate and boss, bushing bore at the back
        translate([HH[0], HH[1], Z_F - 1]) cylinder(d = WIRE_D + 0.3, h = BOSS_L + 2, $fn = 24);
        translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) cylinder(d = BUSH_OD, h = BUSH_L + 1, $fn = 48);
        if (WP != true) socket_housing(true);
        if (WP == true) wp_cuts();
    }
}
// the bushing bore runs next to the cup: without this wall it opened a 1 x 9 mm slit into the rear chamber
module bushing_wall() {
    intersection() {
        translate([HH[0], HH[1], Z_F + ZL_SH]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - ZL_SH, $fn = 48);
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
}

// ---------------------------------------------------------------- waterproof features (UMEH-3W)
NECK_GL = 4;                                 // band point where the cable leaves the sleeve and enters the cup
module at_gland() { translate(NECK[NECK_GL] - [0, 0, NECK_SL / 2 + 0.15]) children(); }   // on the channel floor
GL_BORE = CABLE_D + 2 * GL_CORD * 0.8;       // O-ring on the cable, 20 % radial squeeze
// charge port on the flat back of the power-side cup (mirror place of the slider on the other side), +z inward
module at_pogo() { at_pc() translate([POGO[2], POGO[3], CUP_H]) rotate([180, 0, 0]) children(); }
POST_A = [140, 215, 330];                    // clear of the parts on both trays and of the band spine
TRAY_Z = CUP_H - WALL - POST_L;              // tray back face (local z), components between tray and back wall
module wp_solids() {
    // cable gland boss under the channel floor
    intersection() {
        at_gland() translate([0, 0, -7]) cylinder(d = GL_BORE + 3.2, h = 7, $fn = 32);
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
    // tray posts on the inside of the back
    for (a = POST_A) at_pc() rotate([0, 0, a]) translate([POST_R, 0, TRAY_Z - 2.2]) cylinder(d = 4, h = POST_L + 2.3, $fn = 24);
    if (side != MOD_SIDE) {
        // charge port boss (radial, through the cup wall), slightly proud outside
        at_pogo() {
            translate([0, 0, -0.6]) cylinder(d1 = POGO[0] + 3.0, d2 = POGO[0] + 4.4, h = 0.61, $fn = 40);   // bezel
            cylinder(d = POGO[0] + 4.4, h = POGO[1] + 4.6, $fn = 40);
        }
    } else {
        // power slider rail on the back (dovetail, printed on the top surface; 45 deg flanks)
        at_pc() translate([SLIDER[0], SLIDER[1], CUP_H - 0.01]) slider_rail();
    }
}
module slider_rail() {
    L = SLIDER[2] - SLIDER[1];
    translate([0, 0, 0]) hull() {
        translate([-2.0, 0, 0]) cube([4.0, L, 0.01]);
        translate([-3.0, 0, 1.0]) cube([6.0, L, 0.6]);
    }
    translate([0, L - 1.2, 0]) translate([-3.0, 0, 0]) cube([6.0, 1.2, 3.0]);   // end stop at the ON end
}
module wp_cuts() {
    // cable gland: counterbore for the O-ring on the cable, through hole into the cup
    at_gland() {
        translate([0, 0, -GL_CORD * 1.3]) cylinder(d = GL_BORE, h = GL_CORD * 1.3 + 0.5, $fn = 32);
        translate([0, 0, -8]) cylinder(d = CABLE_D + 0.3, h = 9, $fn = 24);
    }
    if (side != MOD_SIDE) at_pogo() {
        translate([0, 0, -1]) cylinder(d = POGO[0] - 0.6, h = 1.6, $fn = 40);          // face lip (0.6 deep)
        translate([0, 0, 0.6]) cylinder(d = POGO[0] + 0.2, h = POGO[1] + 6, $fn = 40); // body + TPU lock plug
        translate([0, 0, 0.6 + POGO[1] / 2 - 0.8]) cylinder(d = POGO[0] + 2.4, h = 1.6, $fn = 40);   // O-ring groove
    }
}
// visual / purchased parts of the waterproof build
module torus(r, c) { rotate_extrude($fn = 120) translate([r, 0]) circle(d = c, $fn = 16); }
module membrane() { at_pc() translate([0, 0, RING_T]) cylinder(r = POCKET_R - 0.3, h = MEMB_T); }
module orings() {
    rm = (OR_G[0] + OR_G[1]) / 2;
    at_pc() { translate([0, 0, ZL_ADP + OR_CORD * 0.4]) torus(rm, OR_CORD * 0.9); translate([0, 0, ZL_SH - OR_CORD * 0.4]) torus(rm, OR_CORD * 0.9); }
    at_gland() translate([0, 0, -GL_CORD * 0.65]) torus(CABLE_D / 2 + GL_CORD * 0.4, GL_CORD * 0.8);
    if (side != MOD_SIDE) at_pogo() translate([0, 0, 0.6 + POGO[1] / 2]) torus(POGO[0] / 2 + 0.6, 1.2);
}
module pogo_vis() {
    if (side != MOD_SIDE) at_pogo() {
        translate([0, 0, 0.6]) cylinder(d = POGO[0], h = POGO[1], $fn = 40);
        for (s = [-1, 1]) translate([s * 1.4, 0, 0.3]) cylinder(d = 1.2, h = 0.4, $fn = 12);
    }
}
module pogo_plug() {    // TPU friction plug behind the connector (holds it on the face lip; wires through the slot)
    if (side != MOD_SIDE) at_pogo() translate([0, 0, 0.6 + POGO[1]]) difference() {
        cylinder(d = POGO[0] + 0.35, h = 4.0, $fn = 40);
        translate([-1.5, -2.5, -1]) cube([3, 5, 6]);
    }
}
// tray: twisted onto the three posts (keyholes), components face the back wall
module tray() {
    difference() {
        union() {
            at_pc() translate([0, 0, TRAY_Z - 1.2]) {
                difference() { cylinder(r = 25.0, h = 1.2); translate([0, 0, -1]) cylinder(r = 22.5, h = 4); }
                for (a = POST_A) rotate([0, 0, a]) translate([POST_R, 0, 0]) cylinder(d = 7, h = 1.2, $fn = 24);
                linear_extrude(1.2) tray_beds();
            }
        }
        // keyholes: enter at the wide end, turn 12 deg to lock under the post heads
        at_pc() for (a = POST_A) rotate([0, 0, a]) translate([POST_R, 0, TRAY_Z - 3]) cylinder(d = 3.0, h = 5, $fn = 20);
        // notch for the cable gland boss
        at_gland() translate([0, 0, -12]) cylinder(d = GL_BORE + 4.2, h = 12, $fn = 32);
    }
}
// layout (pocket-centre frame): everything below the band spine (which crosses the back from the axis to the rear)
module tray_beds() {
    if (side == MOD_SIDE) {
        translate([0, -12.5]) square([BATT[0] + 2, BATT[1] + 2], center = true);
        translate([SLIDER[0], SLIDER[2] - 4]) square([6, 6], center = true);
        hull() { translate([SLIDER[0], SLIDER[2] - 4]) circle(r = 2); translate([6, -4]) circle(r = 2); }
    } else
        translate([0, -12.5]) square([CHARGER[1] + 2, CHARGER[0] + 2], center = true);
    for (a = POST_A) hull() { rotate([0, 0, a]) translate([POST_R, 0]) circle(r = 2); translate([0, -12]) circle(r = 2); }
}
// module side: battery on the tray, Bluetooth board on top of it, reed switch on a pedestal under the slider;
// other side: charger (and the charge port in the back). 4-core cable in the band: battery +/- to the charger,
// left driver +/- from the board.
module electronics() { color("#1F5E3A") elec("board"); color("#C8E6F0") elec("reed"); color("Silver") elec("battery"); color("#1E3F7A") elec("charger"); }
module elec(what) {
    at_pc() translate([0, 0, TRAY_Z]) {
        if (side == MOD_SIDE) {
            if (what == "battery") translate([-BATT[0] / 2, -12.5 - BATT[1] / 2, 0]) cube([BATT[0], BATT[1], BATT[2]]);
            if (what == "board") translate([-BOARD[0] / 2, -12.5 - BOARD[1] / 2, BATT[2] + 0.1]) cube([BOARD[0], BOARD[1], BOARD[2]]);
            if (what == "reed") translate([SLIDER[0] - 2, SLIDER[2] - 6, 0]) { cube([4, 4, POST_L - 2.6]);
                translate([2, -3, POST_L - 1.5]) rotate([-90, 0, 0]) cylinder(d = 2.2, h = 10, $fn = 12); }
        } else {
            if (what == "charger") translate([-CHARGER[1] / 2, -12.5 - CHARGER[0] / 2, 0]) cube([CHARGER[1], CHARGER[0], CHARGER[2]]);
        }
    }
}
module slider() {    // TPU, snaps over the rail; magnet pressed into its underside pocket; ON at the rail's stop
    L = 9;
    if (side == MOD_SIDE) at_pc() translate([SLIDER[0], SLIDER[2] - 1.2 - L, CUP_H]) difference() {
        hull() { translate([-4.5, 0, 0]) cube([9, L, 0.01]); translate([-4.0, 0.5, 3.2]) cube([8, L - 1, 0.01]); }
        hull() { translate([-2.15, -1, -0.01]) cube([4.3, L + 2, 0.01]); translate([-3.15, -1, 1.0]) cube([6.3, L + 2, 0.7]); }
        translate([0, L / 2, 1.7]) cylinder(d = MAGNET[0] + 0.1, h = MAGNET[1], $fn = 24);
        for (k = [0 : 2]) translate([-4.6, 1.5 + k * 2.5, 2.6]) cube([9.2, 0.8, 1]);         // grip ribs
    }
}
module ring_key() {     // PLA key: two pins in the ring notches, turn the sealed ring with it
    difference() {
        union() {
            cylinder(r = POCKET_R - 2, h = 3);
            translate([-6, -(POCKET_R + 14), 0]) cube([12, 2 * POCKET_R + 28, 4]);
            for (s = [0, 180]) rotate([0, 0, 80 + s]) translate([(AP_R + POCKET_R) / 2, 0, -2.5]) cylinder(d = 2.8, h = 2.6, $fn = 20);
        }
        translate([0, 0, -1]) cylinder(r = AP_R - 6, h = 6);
    }
}

// ---------------------------------------------------------------- front ring
module front_ring() {
    difference() {
        union() {
            cylinder(r = POCKET_R - 0.15, h = RING_T);
            for (a = LUG_A0) rotate([0, 0, a + 1]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180), $fn = 160)
                translate([POCKET_R - 0.5, RING_T - LUG_H]) square([LUG_DEPTH + 0.35, LUG_H - 0.15]);
        }
        translate([0, 0, -1]) cylinder(r = AP_R, h = RING_T + 2);
        translate([0, 0, -0.01]) cylinder(r1 = AP_R + 1.0, r2 = AP_R, h = 1.0);
        // two finger notches on the face (turn by hand)
        for (s = [0, 180]) rotate([0, 0, 80 + s]) translate([(AP_R + POCKET_R) / 2, 0, -0.01]) cylinder(d = 3.2, h = 1.0, $fn = 24);
    }
}

// ---------------------------------------------------------------- TPU adapter per driver
// front lip (aperture 0.88 D) with a conical spring flap at its outer edge; rim seat; back lip.
module adapter(d) { if (WP == true) adapter_w(d); else adapter_a(d); }
// waterproof adapter: 2 mm front lip with the O-ring A groove (membrane side), rim seat, 2 mm back lip with O-ring B
// groove (shoulder side); no lead notch (the leads go back into the dry chamber); 1.25 mm TPU outside the 60 mm rim
module adapter_w(d) {
    v = drv(d); ro = v[1] / 2; rt = v[2]; ap = v[5] / 2;
    RO = POCKET_R - 0.15; lip = (ADAPTER_H - rt) / 2;
    difference() {
        cylinder(r = RO, h = ADAPTER_H);
        translate([0, 0, -1]) cylinder(r = ap, h = 20);
        translate([0, 0, lip]) cylinder(r = ro + 0.05, h = rt + 0.01);
        translate([0, 0, lip + rt - 0.01]) cylinder(r = v[3] / 2 + 0.6, h = 20);
        for (z = [-0.01, ADAPTER_H - OR_GD]) translate([0, 0, z]) difference() {
            cylinder(r = OR_G[1], h = OR_GD + 0.02); translate([0, 0, -1]) cylinder(r = OR_G[0], h = OR_GD + 2); }
        // weight: annular pocket from the back, inside O-ring B (dry side), outside the rim seat wall (small drivers)
        if (OR_G[0] - 1.0 - (ro + 1.2) > 1.5) translate([0, 0, lip]) difference() {
            cylinder(r = OR_G[0] - 1.0, h = ADAPTER_H); translate([0, 0, -1]) cylinder(r = ro + 1.2, h = ADAPTER_H + 2); }
    }
}
module adapter_a(d) {
    v = drv(d); ro = v[1] / 2; rt = v[2]; ap = v[5] / 2;
    RO = POCKET_R - 0.15;
    difference() {
        union() {
            translate([0, 0, 1.0]) cylinder(r = RO, h = ADAPTER_H - 1.0);       // body
            // conical spring flap: 0.8 mm TPU, stands 1.0 mm proud of the body front, flattened by the ring
            difference() {
                translate([0, 0, 0]) cylinder(r1 = RO - 3.0, r2 = RO, h = 1.01);
                translate([0, 0, -0.01]) cylinder(r1 = RO - 3.8, r2 = RO - 0.8, h = 1.03);
            }
            translate([0, 0, 0.6]) cylinder(r = max(ap + 1.5, ro - 1.2), h = 0.41);  // lip ring behind the flap
        }
        translate([0, 0, -1]) cylinder(r = ap, h = 10);                           // aperture
        translate([0, 0, 1.0]) cylinder(r = ro + 0.05, h = rt + 0.01);            // rim seat (driver snaps in)
        translate([0, 0, 1.0 + rt - 0.01]) cylinder(r = v[3] / 2 + 0.6, h = 10);   // back lip opening (basket)
        rotate([0, 0, SOCKET_A - 0]) translate([ro - 2, -1.2, 1.0]) cube([POCKET_R, 2.4, 10]);   // lead notch
    }
}

// ---------------------------------------------------------------- hook
module sweep_tube(pts, d, i0, i1) {
    for (i = [i0 : i1 - 1]) hull() { translate(pts[i]) sphere(d = d, $fn = 20); translate(pts[i + 1]) sphere(d = d, $fn = 20); }
}
module hook_wire() { sweep_tube(HOOK, WIRE_D, 0, len(HOOK) - 1); }
module sleeve_arch() { sweep_tube(HOOK, SIL_ARCH[1], HOOK_ARCH[0], HOOK_ARCH[1]); }
module sleeve_leg() {
    sweep_tube(HOOK, SIL_LEG[1], HOOK_DESC, HOOK_ARCH[0]);
    sweep_tube(HOOK, SIL_LEG[1], HOOK_ARCH[1], len(HOOK) - 1);
    translate(HOOK[len(HOOK) - 1]) sphere(d = SIL_LEG[1] + 1.5, $fn = 24);     // silicone end cap
}
// wide TPU paddle on the rear leg (bears on the back of the pinna; spreads the clamp force)
module paddle() {
    if (PADDLE != undef) {
        w = PADDLE[0]; L = PADDLE[1]; t = PADDLE[2];
        a = atan2(LEG_DIR[1], LEG_DIR[0]);
        difference() {
            translate([PINNA_PT[0], PINNA_PT[1], PINNA_PT[2] - t / 2]) rotate([0, 0, a]) hull()
                for (s = [-1, 1]) translate([s * (L - w) / 2, 0, 0]) cylinder(d = w, h = t, $fn = 40);
            sweep_tube(HOOK, WIRE_D + 0.1, HOOK_ARCH[1], len(HOOK) - 1);
        }
    }
}
// neckband: music wire in a silicone sleeve (first part; the rest runs around the nape) + PETG eye clip on the cup
module neckband() { if (NECK != undef) { sweep_tube(NECK, NECK_SL, 1, len(NECK) - 1); sweep_tube(NECK, NECK_D, 0, 1); } }
// wide soft saddle on the arch (model A final): TPU carrier clipped on the wire + slow-rebound foam strip in a velour sock
module saddle_sector(r0, r1) {
    translate([ARCH_C[0], ARCH_C[1], 0]) rotate([0, 0, ARCH_A[0]])
        rotate_extrude(angle = ARCH_A[1] - ARCH_A[0], $fn = 160)
            translate([r0, Z_ROOT - SADDLE[0] / 2]) offset(r = 0.8) offset(delta = -0.8) square([r1 - r0, SADDLE[0]]);
}
module saddle_foam() { if (SADDLE != undef) { rc = ARCH_R - 2 - SADDLE[2] - SADDLE[1]; saddle_sector(rc, rc + SADDLE[1]); } }
// carrier: thin TPU plate under the foam + a snap-on clip tube around the PTFE-lined wire (light: ~2 g)
module saddle_carrier() {
    if (SADDLE != undef) difference() {
        union() {
            saddle_sector(ARCH_R - 2 - SADDLE[2], ARCH_R - 0.6);
            sweep_tube(HOOK, PTFE[1] + 2.4, HOOK_ARCH[0], HOOK_ARCH[1]);
        }
        sweep_tube(HOOK, PTFE[1] + 0.2, HOOK_ARCH[0], HOOK_ARCH[1]);
    }
}
module bushing() {
    difference() { cylinder(d = BUSH_OD - 0.1, h = BUSH_L); translate([0, 0, -1]) cylinder(d = WIRE_D - 0.15, h = BUSH_L + 2, $fn = 24);
        translate([0, 0, BUSH_L - 1.0]) cylinder(d1 = WIRE_D - 0.15, d2 = WIRE_D + 0.8, h = 1.01, $fn = 24); }
}

// ---------------------------------------------------------------- purchased parts (visual / mass)
module pad() {
    t = PAD_T - PAD_COMP;
    rotate_extrude($fn = 160) hull() {
        translate([PAD_ID / 2 + 4, 4]) circle(r = 4, $fn = 32);
        translate([PAD_OD / 2 - 6, 6]) circle(r = 6, $fn = 32);
        translate([PAD_ID / 2 + 1, t - 1]) square([PAD_OD / 2 - PAD_ID / 2 - 1, 1]);
    }
    // fabric lip wrapped over the flange rim
    translate([0, 0, Z_F - 0.01]) difference() { cylinder(d = FLANGE_OD + 1.6, h = PLATE_T + 2.2); translate([0, 0, -1]) cylinder(d = FLANGE_OD - 6, h = 6); }
}
module front_foam() {
    translate([0, 0, Z_F - 3.0]) difference() {
        cylinder(d = PAD_ID + 4, h = 3.0);
        translate([HH[0], HH[1], -1]) cylinder(d = WIRE_D + 1, h = 5, $fn = 16);
    }
}
module driver_vis(d) {
    v = drv(d);
    difference() { cylinder(r = v[1] / 2, h = v[2]); translate([0, 0, -1]) cylinder(r = v[5] / 2 - 0.5, h = 5); }
    translate([0, 0, 0.3]) difference() { cylinder(r1 = v[5] / 2 - 0.5, r2 = v[3] * 0.18, h = v[4] * 0.25);
        translate([0, 0, -0.01]) cylinder(r1 = v[5] / 2 - 1.1, r2 = v[3] * 0.18 - 0.6, h = v[4] * 0.25 - 0.5); }
    translate([0, 0, v[2]]) cylinder(r1 = v[1] / 2 - 1.5, r2 = v[3] / 2, h = v[4] * 0.5);
    translate([0, 0, v[2] + v[4] * 0.5]) cylinder(r = v[3] / 2 * 0.85, h = v[4] * 0.5 - v[2]);
}
module socket_vis() {
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0])
        translate([-SOCKET[2] / 2, -SOCKET[0] / 2, 0]) cube([SOCKET[2], SOCKET[0], SOCKET[1]]);
}
module fibre() {
    if (WP == true) at_pc() translate([0, 0, TRAY_Z - 1.2 - 4]) cylinder(r = 22, h = 4);   // thin layer under the tray
    else at_pc() translate([0, 0, CUP_H - WALL - FIBRE_T]) cylinder(r = R_HUB - CUP_ROUND, h = FIBRE_T);
}

// ---------------------------------------------------------------- placed parts (head frame)
module placed(p) {
    if (p == "shell") shell();
    if (p == "front_ring") at_pc() translate([0, 0, 0]) front_ring();
    if (p == "adapter") at_pc() translate([0, 0, ZL_ADP]) adapter(D);
    if (p == "driver") at_pc() translate([0, 0, ZL_ADP + 1.0 - 0.0]) driver_vis(D);
    if (p == "bushing") translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) bushing();
    if (p == "wire") hook_wire();
    if (p == "sleeve_arch" && SADDLE == undef) sleeve_arch();
    if (p == "saddle_carrier") saddle_carrier();
    if (p == "saddle_foam") saddle_foam();
    if (p == "sleeve_leg") sleeve_leg();
    if (p == "pad") pad();
    if (p == "front_foam") front_foam();
    if (p == "socket" && WP != true) socket_vis();
    if (p == "paddle") paddle();
    if (p == "neckband") neckband();
    if (p == "fibre") fibre();
    if (p == "logo") logo(side, side == "L");
    if (p == "logo_L") logo("L", true);       // the left letters as the right side's mirror image (viewer)
    if (WP == true) {
        if (p == "membrane") membrane();
        if (p == "orings") orings();
        if (p == "pogo") pogo_vis();
        if (p == "pogo_plug") pogo_plug();
        if (p == "tray") tray();
        if (p == "electronics") electronics();
        if (p == "board" || p == "reed" || p == "battery" || p == "charger") elec(p);
        if (p == "slider") slider();
    }
}
PARTS = ["shell", "front_ring", "adapter", "driver", "bushing", "wire", "sleeve_arch", "sleeve_leg",
         "pad", "front_foam", "socket", "fibre", "paddle", "neckband", "saddle_carrier", "saddle_foam"];
COL = ["#2B2E33", "#A27449", "#1D1F22", "DimGray", "#1D1F22", "Silver", "#3A3D42", "#3A3D42",
       "#2E3036", "#55585E", "Goldenrod", "#8E8A80", "#1D1F22", "#3A3D42", "#1D1F22", "#2E3036"];

module sided() { if (side == "L") mirror([1, 0, 0]) children(); else children(); }

if (part == "assembly") sided() for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
if (part == "section") sided() difference() {
    for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
    translate([-100, -200 + PC[1], -10]) cube([200, 200, 100]);
}
if (pp != "") sided() placed(pp);
// print orientations
if (part == "print_shell") sided() translate([0, 0, -Z_F]) shell();
if (part == "print_front_ring") sided() front_ring();
if (part == "print_adapter") adapter(D);
if (part == "print_bushing") bushing();
if (part == "print_bend_jig") sided() bend_jig();
if (part == "print_tray") sided() translate([0, 0, -(Z_F + TRAY_Z - 1.2)]) tray();
if (part == "print_slider") sided() translate([0, 0, -(Z_F + CUP_H)]) slider();
if (part == "print_pogo_plug") cylinder(d = POGO[0] + 0.35, h = 4.0, $fn = 40);
if (part == "print_ring_key") ring_key();

// wire bending jig (PETG plate with the hook path as a groove; bend the wire around the pins by hand)
module bend_jig() {
    difference() {
        translate([-34, -28, 0]) cube([62, 60, 4]);
        for (i = [HOOK_PLATE + 1 : len(HOOK) - 2]) hull() {
            translate([HOOK[i][0], HOOK[i][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
            translate([HOOK[i + 1][0], HOOK[i + 1][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
        }
    }
}
