// =====================================================================
//  UMEH-3: closed over-ear module on a behind-the-ear hook.
//  One PETG shell for every 40-60 mm driver; no glue, no screws.
//
//  shell        PETG, one piece: flange plate for the round 110 mm pad + closed cup + hook boss + socket housing.
//  front_ring   PETG, 3-lug bayonet (30 deg turn by hand): locks adapter + driver from the front.
//  adapter(D)   TPU 95A, one per driver size: rim seat, aperture lip, conical spring flap (axial preload).
//  bushing      TPU 95A friction bushing in the boss: the hook wire turns and slides in it to set the height.
//  (rotation)   the wire tail is bent into a crank whose pin drops into one of 9 holes in lock_wall().
//  neckband     music wire in a silicone sleeve; its end snaps into a keyhole channel in the back of the cup
//               (the wire end bent into a blind hole), so nothing stands on the back face.
//  hook         music wire, PTFE liner, silicone sleeves (purchased, cut to length; wire bent on the jig).
//  pad          purchased round 110 mm velour pad (visual), front_foam: 3 mm reticulated PU disc.
//  Frame: x forward, y up, z away from the head; origin on the pad axis in the skin plane. Right side;
//  left = mirror([1,0,0]).  Numbers: params3.scad (generated by calc/umeh3/geom.py).
// =====================================================================
include <params3.scad>
part = "assembly";
pp = "";                 // placed part to export alone (head frame), e.g. -D part="none" -D pp="shell"
D = 50;
side = "R";
$fn = $preview ? 64 : 128;

// waterproof build (UMEH-3W): defaults when WP is off; umeh3w.scad includes params3w.scad after this file
MEMB_T = 0; OR_CORD = 1.5; OR_G = [28, 30]; OR_GD = 1.2; CABLE_D = 2.2; GL_CORD = 1.0; GL_ID = 2.0;
POGO = [8.5, 7, 250, 19]; SLIDER = [11, -4, 12]; MAGNET = [6, 2]; MOD_SIDE = "R";
BOARD = [23, 16.5, 3]; CHARGER = [17, 26, 4]; BATT = [30, 20, 4]; POST_R = 24; POST_L = 5.3; POD = undef;

function drv(d) = DRV[search(d, DRV)[0]];
R_HUB = POCKET_R + HUB_WALL;                 // shell outer radius around the pocket centre
ZL_ADP = RING_T + MEMB_T;                    // adapter front face (local z from the plate face)
ZL_SH = RING_T + MEMB_T + ADAPTER_H - ADAPTER_SQ;     // shoulder front face
ZL_CH = ZL_SH + SHOULDER_T;                  // chamber starts
AP_R = 52.8 / 2;                             // front ring opening (60 mm driver aperture)
// lug entry angles (clear of the hook boss and the socket); the waterproof pocket is 1.2 mm wider, its grooves would
// reach the hook wire hole at 49 deg, so the lugs turn to put the hook in the middle of a gap
LUG_A0 = WP == true ? [80, 200, 320] : [20, 140, 260];
HOOK_ANG = atan2(HH[1] - PC[1], HH[0] - PC[0]);
SOCK_Z = 12.0;                               // socket housing centre, local z

module at_pc() { translate([PC[0], PC[1], Z_F]) children(); }

// ---------------------------------------------------------------- shell
module cup_outer2d() {      // (r, zl) about the pocket centre
    hull() {
        square([R_HUB, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - CUP_ROUND]) circle(r = CUP_ROUND, $fn = 64);
        square([0.01, CUP_H]);
    }
}
module cup_inner2d() {
    translate([0, ZL_CH]) hull() {
        square([R_HUB - WALL, 0.01]);
        translate([R_HUB - CUP_ROUND, CUP_H - ZL_CH - CUP_ROUND]) circle(r = CUP_ROUND - WALL, $fn = 64);
        square([0.01, CUP_H - ZL_CH - WALL]);
    }
    translate([0, -1]) square([POCKET_R, ZL_SH + 1]);          // pocket
    translate([0, -1]) square([SHOULDER_RI, ZL_CH + 2]);       // through the shoulder
}
// oval pad (PAD_ODX < PAD_OD): the round flange, pad and front foam are squeezed along x (front-back)
module flange() {
    scale([FLANGE_ODX / FLANGE_OD, 1, 1]) translate([0, 0, Z_F]) difference() {
        union() {
            cylinder(d = FLANGE_OD, h = PLATE_T);
            // rear bead on the rim: the pad's elastic lip hooks behind it
            rotate_extrude($fn = 160) translate([FLANGE_OD / 2 - BEAD_R, PLATE_T + BEAD_R * 0.6]) circle(r = BEAD_R, $fn = 24);
            translate([0, 0, PLATE_T - 0.01]) difference() {
                cylinder(d = FLANGE_OD - 0.4, h = BEAD_R * 0.6 + 0.01);
                translate([0, 0, -1]) cylinder(d = FLANGE_OD - 2 * BEAD_R - 1.6, h = 5);
            }
        }
        // front edge chamfer (the pad lip slides on)
        translate([0, 0, -0.01]) difference() { cylinder(d = FLANGE_OD + 1, h = 0.6); cylinder(d1 = FLANGE_OD - 1.2, d2 = FLANGE_OD + 0.01, h = 0.6); }
    }
}
// rotation lock: arc wall on the back of the plate around the hook boss axis, away from the cup, with a row of holes
// for the pin at the end of the wire crank. LOCK = [r, w, hole, depth, step, n]
module lock_wall() {
    a_out = atan2(HH[1] - PC[1], HH[0] - PC[0]);
    span = (LOCK[5] - 1) * LOCK[4] + 2 * LOCK[1] / LOCK[0] * 180 / PI;
    translate([HH[0], HH[1], Z_F + PLATE_T - 0.01]) difference() {
        rotate([0, 0, a_out - span / 2]) rotate_extrude(angle = span, $fn = 160)
            translate([LOCK[0] - LOCK[1] / 2, 0]) intersection() { offset(r = 1.0) offset(delta = -1.0) translate([0, -2]) square([LOCK[1], BOSS_L - PLATE_T + 2]); square([LOCK[1], BOSS_L]); }
        for (k = [0 : LOCK[5] - 1]) rotate([0, 0, a_out + (k - (LOCK[5] - 1) / 2) * LOCK[4]])
            translate([LOCK[0], 0, BOSS_L - PLATE_T - LOCK[3]]) cylinder(d = LOCK[2], h = LOCK[3] + 1, $fn = 20);
    }
}
module hook_boss_solid() {
    hull() {
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 0.8, $fn = 48);
        translate([HH[0], HH[1], Z_F]) cylinder(d = BUSH_OD + 0.8, h = BOSS_L, $fn = 48);
        at_pc() rotate([0, 0, HOOK_ANG]) translate([R_HUB - 2.5, 0, 0]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - 3, $fn = 48);
    }
}
module socket_housing(cut = false) {
    // 2-pin 0.78 mm female socket, opening facing down-rear; the cable leaves low and backwards
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0]) rotate([0, 0, 0])
        if (!cut) hull() for (i = [-1, 1], j = [-1, 1]) {
            // rounded box (r 2) that grows out of the cup wall, outer end domed
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, -3]) cylinder(r = 2, h = SOCKET[1] + 1.2, $fn = 24);
            translate([i * (SOCKET[2] + 3.2 - 4) / 2, j * (SOCKET[0] + 3.2 - 4) / 2, SOCKET[1] - 1.8]) sphere(r = 2, $fn = 24);
        }
        else {
            translate([-(SOCKET[2] + 0.3) / 2, -(SOCKET[0] + 0.3) / 2, -0.5]) cube([SOCKET[2] + 0.3, SOCKET[0] + 0.3, SOCKET[1] + 5]);
            translate([0, 0, -6]) cylinder(d = 3.0, h = 7, $fn = 24);             // lead hole into the chamber
        }
}
// small pad: the wire passes the plate under the pad and runs in a groove in the plate face to the pad opening
module groove_path(w, z0, h) {
    hull() for (r = [GROOVE_R_IN - 1.5, norm(HH)]) rotate([0, 0, HOOK_A]) translate([r, 0, z0]) cylinder(d = w, h = h, $fn = 24);
}
module groove_rib() { groove_path(WIRE_D + 3.2, Z_F, PLATE_T + 1.6); }
module groove_cut() { groove_path(WIRE_D + 0.4, Z_F - 1, 1 + 0.3 + WIRE_D / 2 + 0.2); }
module bayonet_cut() {
    for (a = LUG_A0) {
        // axial entry channel
        rotate([0, 0, a]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, -1]) square([LUG_DEPTH + 0.1, RING_T + 1.01]);
        // circumferential groove under the retaining lip
        rotate([0, 0, a]) rotate_extrude(angle = TWIST + LUG_W / (POCKET_R * PI / 180) + 2, $fn = 160)
            translate([POCKET_R - 0.1, RING_T - LUG_H - 0.15]) square([LUG_DEPTH + 0.1, LUG_H + 0.15 + 0.01]);
    }
}
// band channel in the back: a trough (spine) inside the back carries the sleeve; keyhole profile (axis 1.2 mm under
// the surface: 3.6 mm opening on the 4 mm sleeve, it snaps in); blind hole for the bent wire end
module neck_spine() {
    if (NECK != undef) intersection() {
        union() { sweep_tube(NECK, NECK_SL + 0.3 + 2 * WALL, 1, NECK_EMB); translate(NECK[1] - [0, 0, NECK_PIN / 2]) sphere(d = WP == true ? 5.5 : 7, $fn = 32); }
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
}
module neck_channel() {
    if (NECK != undef) {
        sweep_tube(NECK, NECK_SL + 0.3, 1, NECK_EMB);
        // let the sleeve leave the channel along its exit direction
        hull() { translate(NECK[NECK_EMB]) sphere(d = NECK_SL + 0.3, $fn = 20); translate(NECK[NECK_EMB + 1]) sphere(d = NECK_SL + 0.3, $fn = 20); }
        translate(NECK[0]) cylinder(d = NECK_D + 0.25, h = NECK[1][2] - NECK[0][2] + 1, $fn = 20);
    }
}
// ---------------------------------------------------------------- brand (commercial finish)
// Raised 0.4 mm wordmark on the flat back + a small side letter; printed in bronze by a filament change at the layer
// where the letters start (the back is the top of the print). A raised 0.8 mm ring in the same colour frames the back.
LOGO_TXT = "UMEH";
LOGO_FONT = "DejaVu Sans:style=Bold";
LOGO_H = 0.4;
logo_in_shell = true;                        // false: the viewer draws the letters as their own (bronze) part
module logo(letter, flip) {
    module flat2d() {
        translate([PC[0], PC[1] - 14.5]) text(LOGO_TXT, size = 5.0, font = LOGO_FONT, halign = "center", valign = "center", spacing = 1.22);
        translate([PC[0], PC[1] + 13.5]) text(letter, size = 3.2, font = LOGO_FONT, halign = "center", valign = "center");
        // accent ring framing the back face (same colour as the letters)
        translate([PC[0], PC[1]]) difference() { circle(r = 22.6, $fn = 160); circle(r = 21.8, $fn = 160); }
    }
    translate([0, 0, Z_F + CUP_H - 0.01]) linear_extrude(LOGO_H + 0.01)
        if (flip) translate([PC[0], 0]) mirror([1, 0]) translate([-PC[0], 0]) flat2d(); else flat2d();
}
module bezel_groove() {
    at_pc() translate([0, 0, CUP_H - 0.4]) difference() { cylinder(r = 22.6, h = 1, $fn = 160); translate([0, 0, -1]) cylinder(r = 21.8, h = 3, $fn = 160); }
}
// concave fillet where the cup meets the flange plate
module cup_fillet() {
    at_pc() rotate_extrude($fn = 160) translate([R_HUB - 0.01, PLATE_T - 0.01]) difference() { square([3, 3]); translate([3, 3]) circle(r = 3, $fn = 32); }
}
module shell() {
    if (logo_in_shell) logo(side, side == "L");
    shell_body();
}
module shell_body() {
    difference() {
        union() {
        difference() {
        union() {
            flange();
            at_pc() rotate_extrude($fn = 160) difference() { cup_outer2d(); }
            cup_fillet();
            hook_boss_solid();
            lock_wall();
            if (WP != true) socket_housing(false);
            if (GROOVE) groove_rib();
        }
        at_pc() rotate_extrude($fn = 160) cup_inner2d();
        at_pc() bayonet_cut();
        if (UNIV != undef) at_pc() univ_slot();
        if (GROOVE) groove_cut();
        // pocket front chamfer
        at_pc() translate([0, 0, -0.01]) cylinder(r1 = POCKET_R + 0.5, r2 = POCKET_R, h = 0.5);
    }
        neck_spine();
        bushing_wall();
        if (WP == true) wp_solids();
        }
        neck_channel();
        // hook: wire passage through plate and boss, bushing bore at the back
        translate([HH[0], HH[1], Z_F - 1]) cylinder(d = WIRE_D + 0.3, h = BOSS_L + 2, $fn = 24);
        translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) cylinder(d = BUSH_OD, h = BUSH_L + 1, $fn = 48);
        if (WP != true) socket_housing(true);
        if (WP == true) wp_cuts();
    }
}
// the bushing bore runs next to the cup: without this wall it opened a 1 x 9 mm slit into the rear chamber
module bushing_wall() {
    intersection() {
        translate([HH[0], HH[1], Z_F + ZL_SH]) cylinder(d = BUSH_OD + 2.4, h = BOSS_L - ZL_SH, $fn = 48);
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
}

// ---------------------------------------------------------------- waterproof features (UMEH-3W)
NECK_GL = 4;                                 // band point where the cable leaves the sleeve and enters the cup
module at_gland() { translate(NECK[NECK_GL] - [0, 0, NECK_SL / 2 + 0.15]) children(); }   // on the channel floor
GL_BORE = CABLE_D + 2 * GL_CORD * 0.8;       // O-ring on the cable, 20 % radial squeeze
// charge port on the flat back of the power-side cup (mirror place of the slider on the other side), +z inward
module at_pogo() { at_pc() translate([POGO[2], POGO[3], CUP_H]) rotate([180, 0, 0]) children(); }
POST_A = [140, 215, 330];                    // clear of the parts on both trays and of the band spine
TRAY_Z = CUP_H - WALL - POST_L;              // tray back face (local z), components between tray and back wall
module wp_solids() {
    // cable gland boss under the channel floor
    intersection() {
        at_gland() translate([0, 0, -7]) cylinder(d = GL_BORE + 3.2, h = 7, $fn = 32);
        at_pc() rotate_extrude($fn = 160) cup_outer2d();
    }
    // tray posts on the inside of the back
    // tray posts: body down to the tray, a 2.8 mm neck through the tray's keyhole slot, a 4.4 mm head under it
    for (a = POST_A) at_pc() rotate([0, 0, a]) translate([POST_R, 0, 0]) {
        translate([0, 0, TRAY_Z]) cylinder(d = 4, h = POST_L + 0.1, $fn = 24);
        translate([0, 0, TRAY_Z - 1.25]) cylinder(d = 2.8, h = 1.3, $fn = 20);
        translate([0, 0, TRAY_Z - 2.05]) cylinder(d = 4.4, h = 0.8, $fn = 24);
    }
    if (side != MOD_SIDE) {
        // charge port boss (radial, through the cup wall), slightly proud outside
        at_pogo() {
            translate([0, 0, -0.6]) cylinder(d1 = POGO[0] + 3.0, d2 = POGO[0] + 4.4, h = 0.61, $fn = 40);   // bezel
            cylinder(d = POGO[0] + 4.4, h = POGO[1] + 4.6, $fn = 40);
        }
    } else {
        // power slider rail on the back (dovetail, printed on the top surface; 45 deg flanks)
        at_pc() translate([SLIDER[0], SLIDER[1], CUP_H - 0.01]) slider_rail();
    }
}
module slider_rail() {
    L = SLIDER[2] - SLIDER[1];
    translate([0, 0, 0]) hull() {
        translate([-2.0, 0, 0]) cube([4.0, L, 0.01]);
        translate([-3.0, 0, 1.0]) cube([6.0, L, 0.6]);
    }
    translate([0, L - 1.2, 0]) translate([-3.0, 0, 0]) cube([6.0, 1.2, 3.0]);   // end stop at the ON end
}
module wp_cuts() {
    // cable gland: counterbore for the O-ring on the cable, through hole into the cup
    at_gland() {
        translate([0, 0, -GL_CORD * 1.3]) cylinder(d = GL_BORE, h = GL_CORD * 1.3 + 0.5, $fn = 32);
        translate([0, 0, -8]) cylinder(d = CABLE_D + 0.3, h = 9, $fn = 24);
    }
    if (side != MOD_SIDE) at_pogo() {
        translate([0, 0, -1]) cylinder(d = POGO[0] - 0.6, h = 1.6, $fn = 40);          // face lip (0.6 deep)
        translate([0, 0, 0.6]) cylinder(d = POGO[0] + 0.2, h = POGO[1] + 6, $fn = 40); // body + TPU lock plug
        translate([0, 0, 0.6 + POGO[1] / 2 - 0.8]) cylinder(d = POGO[0] + 2.4, h = 1.6, $fn = 40);   // O-ring groove
    }
}
// visual / purchased parts of the waterproof build
module torus(r, c) { rotate_extrude($fn = 120) translate([r, 0]) circle(d = c, $fn = 16); }
module membrane() { at_pc() translate([0, 0, RING_T]) cylinder(r = POCKET_R - 0.3, h = MEMB_T); }
module orings() {
    rm = (OR_G[0] + OR_G[1]) / 2;
    at_pc() { translate([0, 0, ZL_ADP + OR_CORD * 0.4]) torus(rm, OR_CORD * 0.9); translate([0, 0, ZL_SH - OR_CORD * 0.4]) torus(rm, OR_CORD * 0.9); }
    at_gland() translate([0, 0, -GL_CORD * 0.65]) torus(CABLE_D / 2 + GL_CORD * 0.4, GL_CORD * 0.8);
    if (side != MOD_SIDE) at_pogo() translate([0, 0, 0.6 + POGO[1] / 2]) torus(POGO[0] / 2 + 0.6, 1.2);
}
module pogo_vis() {
    if (side != MOD_SIDE) at_pogo() {
        translate([0, 0, 0.6]) cylinder(d = POGO[0], h = POGO[1], $fn = 40);
        for (s = [-1, 1]) translate([s * 1.4, 0, 0.3]) cylinder(d = 1.2, h = 0.4, $fn = 12);
    }
}
module pogo_plug() {    // TPU friction plug behind the connector (holds it on the face lip; wires through the slot)
    if (side != MOD_SIDE) at_pogo() translate([0, 0, 0.6 + POGO[1]]) difference() {
        cylinder(d = POGO[0] + 0.35, h = 4.0, $fn = 40);
        translate([-1.5, -2.5, -1]) cube([3, 5, 6]);
    }
}
// tray: twisted onto the three posts (keyholes), components face the back wall
module tray() {
    difference() {
        union() {
            at_pc() translate([0, 0, TRAY_Z - 1.2]) {
                difference() { cylinder(r = 25.0, h = 1.2); translate([0, 0, -1]) cylinder(r = 22.5, h = 4); }
                for (a = POST_A) rotate([0, 0, a]) translate([POST_R, 0, 0]) cylinder(d = 7, h = 1.2, $fn = 24);
                linear_extrude(1.2) tray_beds();
            }
        }
        // keyholes: the heads pass the wide end (4.8 mm), then turn the tray 12 deg so the necks sit in the 3 mm slots
        at_pc() for (a = POST_A) translate([0, 0, TRAY_Z - 3]) {
            rotate([0, 0, a - 12]) translate([POST_R, 0, 0]) cylinder(d = 4.8, h = 5, $fn = 24);
            rotate([0, 0, a - 12]) rotate_extrude(angle = 12, $fn = 120) translate([POST_R - 1.5, 0]) square([3.0, 5]);
            rotate([0, 0, a]) translate([POST_R, 0, 0]) cylinder(d = 3.0, h = 5, $fn = 20);
        }
        // notch for the cable gland boss
        at_gland() translate([0, 0, -12]) cylinder(d = GL_BORE + 4.2, h = 12, $fn = 32);
        // clearance for the pogo boss (charger side)
        if (side != MOD_SIDE) at_pogo() cylinder(d = POGO[0] + 5.4, h = 30, $fn = 40);
    }
}
// layout (pocket-centre frame): everything below the band spine (which crosses the back from the axis to the rear)
// one 503030 cell (30 x 30 x 5) on each tray, under the band spine (the tray sits low for it); module side: Bluetooth
// board on the cell + reed switch on a pedestal under the slider; other side: charger on the cell. The two cells work
// in parallel through the band cable (4 cores: cell +/- to the charger side, left driver +/- from the board).
BATT_C = [0, -10];
EL_Z = POD == undef ? BATT[2] + 0.1 : 0.1;   // board / charger sit on the cell, or on the tray when the cell is in the nape pod
module tray_beds() {
    if (POD == undef) translate(BATT_C) square([BATT[0] + 1, BATT[1] + 1], center = true);
    if (side == MOD_SIDE) {
        translate([SLIDER[0], SLIDER[2] - 4]) square([6, 6], center = true);
        hull() { translate([SLIDER[0], SLIDER[2] - 4]) circle(r = 2); translate([6, 0]) circle(r = 2); }
    }
    for (a = POST_A) hull() { rotate([0, 0, a]) translate([POST_R, 0]) circle(r = 2); translate([0, -12]) circle(r = 2); }
}
module electronics() { color("#1F5E3A") elec("board"); color("#C8E6F0") elec("reed"); color("Silver") elec("battery"); color("#1E3F7A") elec("charger"); }
module elec(what) {
    at_pc() translate([0, 0, TRAY_Z]) {
        if (what == "battery" && POD == undef) translate([BATT_C[0] - BATT[0] / 2, BATT_C[1] - BATT[1] / 2, 0]) cube([BATT[0], BATT[1], BATT[2]]);
        if (side == MOD_SIDE) {
            if (what == "board") translate([-BOARD[0] / 2, -12 - BOARD[1] / 2, EL_Z]) cube([BOARD[0], BOARD[1], BOARD[2]]);
            if (what == "reed") translate([SLIDER[0] - 2, SLIDER[2] - 6, 0]) { cube([4, 4, POST_L - 2.6]);
                translate([2, -3, POST_L - 1.5]) rotate([-90, 0, 0]) cylinder(d = 2.2, h = 10, $fn = 12); }
        } else {
            if (what == "charger") translate([-CHARGER[1] / 2, -12.5 - CHARGER[0] / 2, EL_Z]) cube([CHARGER[1], CHARGER[0], CHARGER[2]]);
        }
    }
}
module slider() {    // TPU, snaps over the rail; magnet pressed into its underside pocket; ON at the rail's stop
    L = 9;
    if (side == MOD_SIDE) at_pc() translate([SLIDER[0], SLIDER[2] - 1.2 - L, CUP_H]) difference() {
        hull() { translate([-4.5, 0, 0]) cube([9, L, 0.01]); translate([-4.0, 0.5, 3.2]) cube([8, L - 1, 0.01]); }
        hull() { translate([-2.15, -1, -0.01]) cube([4.3, L + 2, 0.01]); translate([-3.15, -1, 1.0]) cube([6.3, L + 2, 0.7]); }
        translate([0, L / 2, 1.7]) cylinder(d = MAGNET[0] + 0.1, h = MAGNET[1], $fn = 24);
        for (k = [0 : 2]) translate([-4.6, 1.5 + k * 2.5, 2.6]) cube([9.2, 0.8, 1]);         // grip ribs
    }
}
module ring_key() {     // PLA key: two pins in the ring notches, turn the sealed ring with it
    difference() {
        union() {
            cylinder(r = POCKET_R - 2, h = 3);
            translate([-6, -(POCKET_R + 14), 0]) cube([12, 2 * POCKET_R + 28, 4]);
            for (s = [0, 180]) rotate([0, 0, 80 + s]) translate([(AP_R + POCKET_R) / 2, 0, -2.5]) cylinder(d = 2.8, h = 2.6, $fn = 20);
        }
        translate([0, 0, -1]) cylinder(r = AP_R - 6, h = 6);
    }
}

// ---------------------------------------------------------------- front ring
module front_ring() {
    difference() {
        union() {
            cylinder(r = POCKET_R - 0.15, h = RING_T);
            for (a = LUG_A0) rotate([0, 0, a + 1]) rotate_extrude(angle = LUG_W / (POCKET_R * PI / 180), $fn = 160)
                translate([POCKET_R - 0.5, RING_T - LUG_H]) square([LUG_DEPTH + 0.35, LUG_H - 0.15]);
        }
        translate([0, 0, -1]) cylinder(r = AP_R, h = RING_T + 2);
        translate([0, 0, -0.01]) cylinder(r1 = AP_R + 1.0, r2 = AP_R, h = 1.0);
        // two finger notches on the face (turn by hand)
        for (s = [0, 180]) rotate([0, 0, 80 + s]) translate([(AP_R + POCKET_R) / 2, 0, -0.01]) cylinder(d = 3.2, h = 1.0, $fn = 24);
    }
    if (UNIV != undef) front_spokes();      // universal seat: back the front EVA for small drivers
}

// ---------------------------------------------------------------- TPU adapter per driver
// front lip (aperture 0.88 D) with a conical spring flap at its outer edge; rim seat; back lip.
module adapter(d) { if (WP == true) adapter_w(d); else adapter_a(d); }
// waterproof adapter: 2 mm front lip with the O-ring A groove (membrane side), rim seat, 2 mm back lip with O-ring B
// groove (shoulder side); no lead notch (the leads go back into the dry chamber); 1.25 mm TPU outside the 60 mm rim
module adapter_w(d) {
    v = drv(d); ro = v[1] / 2; rt = v[2]; ap = v[5] / 2;
    RO = POCKET_R - 0.15; lip = (ADAPTER_H - rt) / 2;
    difference() {
        cylinder(r = RO, h = ADAPTER_H);
        translate([0, 0, -1]) cylinder(r = ap, h = 20);
        translate([0, 0, lip]) cylinder(r = ro + 0.05, h = rt + 0.01);
        translate([0, 0, lip + rt - 0.01]) cylinder(r = v[3] / 2 + 0.6, h = 20);
        for (z = [-0.01, ADAPTER_H - OR_GD]) translate([0, 0, z]) difference() {
            cylinder(r = OR_G[1], h = OR_GD + 0.02); translate([0, 0, -1]) cylinder(r = OR_G[0], h = OR_GD + 2); }
        // weight: annular pocket from the back, inside O-ring B (dry side), outside the rim seat wall (small drivers)
        if (OR_G[0] - 1.0 - (ro + 1.2) > 1.5) translate([0, 0, lip]) difference() {
            cylinder(r = OR_G[0] - 1.0, h = ADAPTER_H); translate([0, 0, -1]) cylinder(r = ro + 1.2, h = ADAPTER_H + 2); }
    }
}
module adapter_a(d) {
    v = drv(d); ro = v[1] / 2; rt = v[2]; ap = v[5] / 2;
    RO = POCKET_R - 0.15;
    difference() {
        union() {
            translate([0, 0, 1.0]) cylinder(r = RO, h = ADAPTER_H - 1.0);       // body
            // conical spring flap: 0.8 mm TPU, stands 1.0 mm proud of the body front, flattened by the ring
            difference() {
                translate([0, 0, 0]) cylinder(r1 = RO - 3.0, r2 = RO, h = 1.01);
                translate([0, 0, -0.01]) cylinder(r1 = RO - 3.8, r2 = RO - 0.8, h = 1.03);
            }
            translate([0, 0, 0.6]) cylinder(r = max(ap + 1.5, ro - 1.2), h = 0.41);  // lip ring behind the flap
        }
        translate([0, 0, -1]) cylinder(r = ap, h = 10);                           // aperture
        translate([0, 0, 1.0]) cylinder(r = ro + 0.05, h = rt + 0.01);            // rim seat (driver snaps in)
        translate([0, 0, 1.0 + rt - 0.01]) cylinder(r = v[3] / 2 + 0.6, h = 10);   // back lip opening (basket)
        if (CONTACTS) contact_cuts(d);
        else rotate([0, 0, SOCKET_A - 0]) translate([ro - 2, -1.2, 1.0]) cube([POCKET_R, 2.4, 10]);   // lead notch
    }
}

// ---------------------------------------------------------------- universal driver seat (UMEH-3 oval, 2026-10-07)
// UNIV = [F, M, S, B thickness, strip t, strip w, strip gap, spokes n, spoke w, spoke r_in, rib w, rib proud]. One set for every 40-60 mm
// driver, each layer pre-scored at the five sizes; the user pops out the inner rings down to the driver's size:
//   F craft EVA -> aperture (front clamp + seal; backed by the spokes of the front ring for small drivers)
//   M craft EVA -> rim OD (centres and grips the rim)
//   S craft EVA -> basket (spring behind the contacts: two straight parallel bronze strips on its front face)
//   B PETG break-away plate -> basket (rigid back for small drivers; concentric rings joined by thin bridges)
// The strip tails run back along the pocket wall through a slot in the shoulder to the socket wires.
function univ_z(i) = i == 0 ? 0 : UNIV[i - 1] + univ_z(i - 1);
function univ_hole(i, d) = let(v = drv(d)) i == 0 ? v[5] / 2 : i == 1 ? v[1] / 2 - 0.15 : v[3] / 2 + 0.6;
module univ_layer(i, d) {
    translate([0, 0, univ_z(i)]) difference() {
        cylinder(r = POCKET_R - 0.15, h = UNIV[i]);
        translate([0, 0, -1]) cylinder(r = univ_hole(i, d), h = UNIV[i] + 2);
        // remaining score lines (EVA) / break grooves (PETG) outside the popped-out hole, visual
        for (k = [0 : len(DRV) - 1]) let(rk = univ_hole(i, DRV[k][0])) if (rk > univ_hole(i, d) + 0.3)
            translate([0, 0, UNIV[i] - 0.5]) difference() { cylinder(r = rk + 0.2, h = 1); translate([0, 0, -1]) cylinder(r = rk - 0.2, h = 3); }
    }
}
module eva_seat(d) { for (i = [0 : 2]) univ_layer(i, d); }
module break_plate(d) { univ_layer(3, d); }
module strips_vis(d) {
    t = UNIV[4]; w = UNIV[5]; g = UNIV[6]; z = univ_z(2); r0 = univ_hole(2, d); r1 = POCKET_R - 0.25;
    rotate([0, 0, SOCKET_A]) for (s = [-1, 1]) translate([0, s * (g + w) / 2, 0]) {
        translate([r0, -w / 2, z - t]) cube([r1 - r0, w, t]);
        translate([r1 - t, -w / 2, z - t]) cube([t, w, ADAPTER_H - z + t + SHOULDER_T + 3]);
    }
}
// spokes + hub + a rib at the bore, all UNIV[11] proud of the ring's back: only they squeeze the EVA stack
module front_spokes() {
    h = RING_T + UNIV[11];
    for (k = [0 : UNIV[7] - 1]) rotate([0, 0, 90 + k * 360 / UNIV[7]])
        translate([UNIV[9], -UNIV[8] / 2, 0]) cube([AP_R - UNIV[9] + 0.5, UNIV[8], h]);
    difference() { cylinder(r = UNIV[9] + 1.2, h = h); translate([0, 0, -1]) cylinder(r = UNIV[9], h = h + 2); }
    difference() { cylinder(r = AP_R + UNIV[10], h = h); translate([0, 0, -1]) cylinder(r = AP_R, h = h + 2); }
}
module univ_slot() {     // shoulder slot for the two strip tails (shell cut, pocket frame)
    w = 2 * UNIV[5] + UNIV[6] + 1.0;
    rotate([0, 0, SOCKET_A]) translate([POCKET_R - 1.4, -w / 2, ZL_SH - 0.5]) cube([1.6, w, SHOULDER_T + 1]);
}

// ---------------------------------------------------------------- solder-free driver contacts (2026-10-06)
// Two phosphor-bronze leaf springs (0.2 x 2 mm) lie on the front face of the adapter's back lip, on the driver's back
// flange, one each side of a 1.6 mm TPU rib at SOCKET_A. Each is a cantilever: fixed end (CT_FIX) in a 0.25 mm recess,
// free part (CT_FREE) over a shallow window in the lip (floor = bend stop), bent up CT_PRE so it presses the driver's solder pad when the
// driver snaps in. The driver is turned so its two pads straddle the rib. The fixed end's 3 mm tab goes back through
// a slot; the wire from the socket is soldered to it once at the bench (never at the driver), then runs in a groove in
// the lip's back face to the open chamber (r < SHOULDER_RI). Force and stress: calc/studies/driver_contacts.py.
CONTACTS = true;
CT = [0.2, 2.0, 1.6];                 // leaf thickness, width, rib between the leaves
CT_FREE = 8.0; CT_FIX = 3.5; CT_PRE = 0.5; CT_TAB = 3.0;
CT_STOP = 0.2;                         // window floor this far behind the flat leaf: caps its bend (stress) for raised pads
function ct_rc(d) = let(v = drv(d)) (v[3] / 2 + 0.6 + v[1] / 2) / 2;      // mid radius of the driver's back flange
function ct_deg(d, L) = L / ct_rc(d) * 180 / PI;
module ct_sector(r0, r1, a0, a1) {
    rotate([0, 0, min(a0, a1)]) rotate_extrude(angle = abs(a1 - a0), $fn = 240) translate([r0, 0]) square([r1 - r0, 1]);
}
// angle span of one leaf, side s = +1 / -1 from the rib
function ct_a(d, s, L) = SOCKET_A + s * (ct_deg(d, CT[2] / 2) + ct_deg(d, L));
module contact_cuts(d) {
    v = drv(d); rc = ct_rc(d); rt = v[2]; zl = 1.0 + rt; w = CT[1] / 2 + 0.3;
    for (s = [-1, 1]) {
        a0 = ct_a(d, s, 0); a1 = ct_a(d, s, CT_FREE); a2 = ct_a(d, s, CT_FREE + CT_FIX);
        translate([0, 0, zl - 0.01]) scale([1, 1, CT[0] + CT_STOP + 0.01]) ct_sector(rc - w, rc + w, a0, a1);   // window
        translate([0, 0, zl - 0.01]) scale([1, 1, CT[0] + 0.06]) ct_sector(rc - w, rc + w, a1, a2 + 0.5); // recess
        rotate([0, 0, a2]) translate([rc - w, -0.35, zl - 0.01]) cube([2 * w, 0.7, 10]);                 // tab slot
        // wire groove on the back face, from the tab inwards to the open chamber
        rotate([0, 0, a2 + s * ct_deg(d, 1.0)]) translate([min(rc, SHOULDER_RI) - 3.5, -0.4, ADAPTER_H - 0.6])
            cube([max(rc, SHOULDER_RI) - min(rc, SHOULDER_RI) + 3.5 + w, 0.8, 1]);
    }
    // index mark on the front lip: the driver's pads go here
    rotate([0, 0, SOCKET_A]) translate([v[5] / 2 + 0.4, -0.5, -0.01]) cube([1.2, 1.0, 0.41]);
}
// the leaves as fitted (visual): free part tilted up CT_PRE at the tip, dimple at the tip, tab bent back
module contacts_vis(d) {
    v = drv(d); rc = ct_rc(d); rt = v[2]; zl = 1.0 + rt; n = 12;
    for (s = [-1, 1]) {
        a1 = ct_a(d, s, CT_FREE); a2 = ct_a(d, s, CT_FREE + CT_FIX);
        translate([0, 0, zl]) scale([1, 1, CT[0]]) ct_sector(rc - CT[1] / 2, rc + CT[1] / 2, a1, a2);   // in the recess
        for (i = [0 : n - 1]) {           // free part: cubic bend, tip CT_PRE proud (towards the driver, -z)
            u0 = i / n; u1 = (i + 1) / n;
            hull() for (u = [u0, u1]) rotate([0, 0, ct_a(d, s, CT_FREE * (1 - u))])
                translate([rc - CT[1] / 2, -0.01, zl - CT_PRE * (3 * u * u - u * u * u) / 2]) cube([CT[1], 0.02, CT[0]]);
        }
        rotate([0, 0, ct_a(d, s, 0.6)]) translate([rc, 0, zl - CT_PRE + 0.15]) sphere(r = 0.5, $fn = 16);   // dimple
        rotate([0, 0, a2]) translate([rc - CT[1] / 2, -0.1, zl]) cube([CT[1], 0.2, CT_TAB + ADAPTER_H - zl]);
    }
}

// ---------------------------------------------------------------- hook
module sweep_tube(pts, d, i0, i1) {
    for (i = [i0 : i1 - 1]) hull() { translate(pts[i]) sphere(d = d, $fn = 20); translate(pts[i + 1]) sphere(d = d, $fn = 20); }
}
module hook_wire() { sweep_tube(HOOK, WIRE_D, 0, len(HOOK) - 1); }
module sleeve_arch() { sweep_tube(HOOK, SIL_ARCH[1], HOOK_ARCH[0], HOOK_ARCH[1]); }
module sleeve_leg() {
    sweep_tube(HOOK, SIL_LEG[1], HOOK_DESC, HOOK_ARCH[0]);
    sweep_tube(HOOK, SIL_LEG[1], HOOK_ARCH[1], len(HOOK) - 1);
    translate(HOOK[len(HOOK) - 1]) sphere(d = SIL_LEG[1] + 1.5, $fn = 24);     // silicone end cap
}
// wide TPU paddle on the rear leg (bears on the back of the pinna; spreads the clamp force)
module paddle() {
    if (PADDLE != undef) {
        w = PADDLE[0]; L = PADDLE[1]; t = PADDLE[2];
        a = atan2(LEG_DIR[1], LEG_DIR[0]);
        difference() {
            translate([PINNA_PT[0], PINNA_PT[1], PINNA_PT[2] - t / 2]) rotate([0, 0, a]) hull()
                for (s = [-1, 1]) translate([s * (L - w) / 2, 0, 0]) cylinder(d = w, h = t, $fn = 40);
            sweep_tube(HOOK, WIRE_D + 0.1, HOOK_ARCH[1], len(HOOK) - 1);
        }
    }
}
// neckband: music wire in a silicone sleeve (first part; the rest runs around the nape) + PETG eye clip on the cup
module neckband() { if (NECK != undef) { sweep_tube(NECK, NECK_SL, 1, len(NECK) - 1); sweep_tube(NECK, NECK_D, 0, 1); } }
// wide soft saddle on the arch (model A final): TPU carrier clipped on the wire + slow-rebound foam strip in a velour sock
module saddle_sector(r0, r1) {
    translate([ARCH_C[0], ARCH_C[1], 0]) rotate([0, 0, ARCH_A[0]])
        rotate_extrude(angle = ARCH_A[1] - ARCH_A[0], $fn = 160)
            translate([r0, Z_ROOT - SADDLE[0] / 2]) offset(r = 0.8) offset(delta = -0.8) square([r1 - r0, SADDLE[0]]);
}
module saddle_foam() { if (SADDLE != undef) { rc = ARCH_R - 2 - SADDLE[2] - SADDLE[1]; saddle_sector(rc, rc + SADDLE[1]); } }
// carrier: thin TPU plate under the foam + a snap-on clip tube around the PTFE-lined wire (light: ~2 g)
module saddle_carrier() {
    if (SADDLE != undef) difference() {
        union() {
            saddle_sector(ARCH_R - 2 - SADDLE[2], ARCH_R - 0.6);
            sweep_tube(HOOK, PTFE[1] + 2.4, HOOK_ARCH[0], HOOK_ARCH[1]);
        }
        sweep_tube(HOOK, PTFE[1] + 0.2, HOOK_ARCH[0], HOOK_ARCH[1]);
    }
}
module bushing() {
    difference() { cylinder(d = BUSH_OD - 0.1, h = BUSH_L); translate([0, 0, -1]) cylinder(d = WIRE_D - 0.15, h = BUSH_L + 2, $fn = 24);
        translate([0, 0, BUSH_L - 1.0]) cylinder(d1 = WIRE_D - 0.15, d2 = WIRE_D + 0.8, h = 1.01, $fn = 24); }
}

// ---------------------------------------------------------------- purchased parts (visual / mass)
module pad() {
    t = PAD_T - PAD_COMP;
    difference() {
        scale([PAD_ODX / PAD_OD, 1, 1]) rotate_extrude($fn = 160) hull() {
            translate([PAD_ID / 2 + 4, 4]) circle(r = 4, $fn = 32);
            translate([PAD_OD / 2 - 6, 6]) circle(r = 6, $fn = 32);
            translate([PAD_ID / 2 + 1, t - 1]) square([PAD_OD / 2 - PAD_ID / 2 - 1, 1]);
        }
        // the opening at the head face (its own aspect ratio when oval)
        scale([PAD_IDX / PAD_ID, 1, 1]) translate([0, 0, -1]) cylinder(d = PAD_ID, h = t + 2);
    }
    // fabric lip wrapped over the flange rim
    scale([FLANGE_ODX / FLANGE_OD, 1, 1]) translate([0, 0, Z_F - 0.01])
        difference() { cylinder(d = FLANGE_OD + 1.6, h = PLATE_T + 2.2); translate([0, 0, -1]) cylinder(d = FLANGE_OD - 6, h = 6); }
}
module front_foam() {
    translate([0, 0, Z_F - 3.0]) difference() {
        scale([(PAD_IDX + 4) / (PAD_ID + 4), 1, 1]) cylinder(d = PAD_ID + 4, h = 3.0);
        translate([HH[0], HH[1], -1]) cylinder(d = WIRE_D + 1, h = 5, $fn = 16);
    }
}
module driver_vis(d) {
    v = drv(d);
    difference() { cylinder(r = v[1] / 2, h = v[2]); translate([0, 0, -1]) cylinder(r = v[5] / 2 - 0.5, h = 5); }
    translate([0, 0, 0.3]) difference() { cylinder(r1 = v[5] / 2 - 0.5, r2 = v[3] * 0.18, h = v[4] * 0.25);
        translate([0, 0, -0.01]) cylinder(r1 = v[5] / 2 - 1.1, r2 = v[3] * 0.18 - 0.6, h = v[4] * 0.25 - 0.5); }
    translate([0, 0, v[2]]) cylinder(r1 = WP == true ? v[3] / 2 : v[1] / 2 - 1.5, r2 = v[3] / 2, h = v[4] * 0.5);
    translate([0, 0, v[2] + v[4] * 0.5]) cylinder(r = v[3] / 2 * 0.85, h = v[4] * 0.5 - v[2]);
}
module socket_vis() {
    at_pc() rotate([0, 0, SOCKET_A]) translate([R_HUB - 1.0, 0, SOCK_Z]) rotate([0, 90, 0])
        translate([-SOCKET[2] / 2, -SOCKET[0] / 2, 0]) cube([SOCKET[2], SOCKET[0], SOCKET[1]]);
}
module fibre() {
    if (WP == true) at_pc() translate([0, 0, TRAY_Z - 1.2 - 1.5]) cylinder(r = 20, h = 1.5);   // thin layer under the tray
    else at_pc() translate([0, 0, CUP_H - WALL - FIBRE_T]) cylinder(r = R_HUB - CUP_ROUND, h = FIBRE_T);
}

// ---------------------------------------------------------------- placed parts (head frame)
module placed(p) {
    if (p == "shell") shell();
    if (p == "front_ring") at_pc() translate([0, 0, 0]) front_ring();
    if (p == "adapter") at_pc() translate([0, 0, ZL_ADP]) if (UNIV != undef) eva_seat(D); else adapter(D);
    if (p == "break_plate" && UNIV != undef) at_pc() translate([0, 0, ZL_ADP]) break_plate(D);
    if (p == "contacts" && CONTACTS && WP != true) at_pc() translate([0, 0, ZL_ADP]) if (UNIV != undef) strips_vis(D); else contacts_vis(D);
    if (p == "driver") at_pc() translate([0, 0, ZL_ADP + (WP == true ? (ADAPTER_H - drv(D)[2]) / 2 : UNIV != undef ? UNIV[0] : 1.0)]) driver_vis(D);
    if (p == "bushing") translate([HH[0], HH[1], Z_F + BOSS_L - BUSH_L]) bushing();
    if (p == "wire") hook_wire();
    if (p == "sleeve_arch" && SADDLE == undef) sleeve_arch();
    if (p == "saddle_carrier") saddle_carrier();
    if (p == "saddle_foam") saddle_foam();
    if (p == "sleeve_leg") sleeve_leg();
    if (p == "pad") pad();
    if (p == "front_foam") front_foam();
    if (p == "socket" && WP != true) socket_vis();
    if (p == "paddle") paddle();
    if (p == "neckband") neckband();
    if (p == "fibre") fibre();
    if (p == "logo") logo(side, side == "L");
    if (p == "logo_L") logo("L", true);       // the left letters as the right side's mirror image (viewer)
    if (WP == true) {
        if (p == "membrane") membrane();
        if (p == "orings") orings();
        if (p == "pogo") pogo_vis();
        if (p == "pogo_plug") pogo_plug();
        if (p == "tray") tray();
        if (p == "electronics") electronics();
        if (p == "board" || p == "reed" || p == "battery" || p == "charger") elec(p);
        if (p == "slider") slider();
    }
}
PARTS = ["shell", "front_ring", "adapter", "driver", "bushing", "wire", "sleeve_arch", "sleeve_leg",
         "pad", "front_foam", "socket", "fibre", "paddle", "neckband", "saddle_carrier", "saddle_foam"];
COL = ["#2B2E33", "#A27449", "#1D1F22", "DimGray", "#1D1F22", "Silver", "#3A3D42", "#3A3D42",
       "#2E3036", "#55585E", "Goldenrod", "#8E8A80", "#1D1F22", "#3A3D42", "#1D1F22", "#2E3036"];

module sided() { if (side == "L") mirror([1, 0, 0]) children(); else children(); }

if (part == "assembly") sided() for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
if (part == "section") sided() difference() {
    for (i = [0 : len(PARTS) - 1]) color(COL[i]) placed(PARTS[i]);
    translate([-100, -200 + PC[1], -10]) cube([200, 200, 100]);
}
if (pp != "") sided() placed(pp);
// print orientations
if (part == "print_shell") sided() translate([0, 0, -Z_F]) shell();
if (part == "print_front_ring") sided() front_ring();
if (part == "print_adapter") adapter(D);
if (part == "print_bushing") bushing();
if (part == "print_bend_jig") sided() bend_jig();
if (part == "print_tray") sided() translate([0, 0, -(Z_F + TRAY_Z - 1.2)]) tray();
if (part == "print_slider") sided() translate([0, 0, -(Z_F + CUP_H)]) slider();
if (part == "print_pogo_plug") cylinder(d = POGO[0] + 0.35, h = 4.0, $fn = 40);
if (part == "print_ring_key") ring_key();

// wire bending jig (PETG plate with the hook path as a groove; bend the wire around the pins by hand)
module bend_jig() {
    difference() {
        translate([-34, -28, 0]) cube([62, 60, 4]);
        for (i = [HOOK_PLATE + 1 : len(HOOK) - 2]) hull() {
            translate([HOOK[i][0], HOOK[i][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
            translate([HOOK[i + 1][0], HOOK[i + 1][1], 2.6]) cylinder(d = WIRE_D + 0.3, h = 3, $fn = 16);
        }
    }
}

// ---------------------------------------------------------------------------------------------------------------------
// nape battery pod (UMEH-3W, user 2026-10-04): one 603450 cell in a sealed PETG box at the back of the neckband,
// resting on the nape (user's card "apoiar e aliviar"): the neck side is curved (neck r ~70 mm) and carries a 3 mm
// self-adhesive neoprene strip, so the neck takes most of the pod's weight instead of the ear hooks.
// Pod frame: x along the band, y up, z away from the neck (z = 0 at the middle of the curved face).
// Each half-band ends at the pod: the silicone tube presses into an end socket over a 2 x 1 O-ring on the cable (same
// gland as the cups); the steel wire leaves the tube through a slit, enters a hole in the block beside the socket and
// its 90 deg tail drops into a cross hole (outside the sealed box). The lid closes on a printed TPU gasket with
// 4 M2 x 8 pan-head self-tapping screws in corner bosses; the gasket also seals round each screw.
// Home printing: base on its long side (no supports), lid flat, gasket flat in TPU.
PD_W = 1.2; PD_FL = 1.2; PD_LID = 1.2; PD_GK = 0.8; PD_RIM = [2.0, 0.8];   // walls, floor, lid, gasket, lid edge frame
PD_RN = 70; PD_NEO = 3;                    // neck radius, neoprene thickness
PD_RB = PD_RN + PD_NEO;                    // radius of the base's neck face
PD_BOSS = 4.6; PD_SEAL = 2.4;            // screw bosses, gasket land width
function pd_cav() = [POD[0] + 2 + 2 * PD_BOSS + 1.2, POD[1] + 1.2, POD[2] + 1.4];
function pd_out() = [pd_cav()[0] + 2 * PD_W, pd_cav()[1] + 2 * PD_W, PD_FL + pd_cav()[2]];
function pd_zf(x) = sqrt(PD_RB * PD_RB - x * x) - PD_RB;   // neck face height at x
PD_SOCK_Z = 0.5; PD_WIRE_Y = -7.5; PD_SOCK_L = 6;
function pd_bx() = pd_cav()[0] / 2 - PD_BOSS / 2;
function pd_by() = pd_cav()[1] / 2 - PD_BOSS / 2;
PD_SCR = [[1, 1], [1, -1], [-1, 1], [-1, -1]];
function pd_scr(s) = [s[0] * pd_bx(), s[1] * pd_by()];
module pd_outline(o = 0) { offset(r = 4 + o) offset(r = -4) square([pd_out()[0], pd_out()[1]], center = true); }
module pd_neck_cyl(r) { translate([0, 0, -PD_RB]) rotate([90, 0, 0]) cylinder(r = r, h = 100, center = true, $fn = 360); }
module pd_shell() { difference() { translate([0, 0, -20]) linear_extrude(20 + pd_out()[2]) pd_outline(); pd_neck_cyl(PD_RB); } }
module pod_base() {
    c = pd_cav(); o = pd_out(); xe = o[0] / 2;
    difference() {
        union() {
            difference() {
                pd_shell();
                difference() {                                                      // the cavity, above the curved floor
                    translate([-c[0] / 2, -c[1] / 2, -20]) cube([c[0], c[1], 40]);
                    pd_neck_cyl(PD_RB + PD_FL);
                    for (s = PD_SCR) translate([pd_scr(s)[0], pd_scr(s)[1], -30]) cylinder(d = PD_BOSS, h = 60, $fn = 24);
                }
            }
            translate([0, 0, o[2] - 1.2]) linear_extrude(1.2) difference() { pd_outline(); pd_outline(-PD_SEAL); }   // 2.4 mm seal ledge
            intersection() { pd_shell(); for (sx = [-1, 1]) translate([sx * 18 - 0.6, -c[1] / 2, -20]) cube([1.2, c[1], 20 + PD_FL]); }   // cell rests
            for (sx = [-1, 1]) {
                translate([sx * xe, 0, PD_SOCK_Z]) rotate([0, sx * 90, 0]) cylinder(d = 8.6, h = PD_SOCK_L, $fn = 40);
                hull() for (dz = [-2.4, 2.4]) translate([sx * xe, PD_WIRE_Y, PD_SOCK_Z + dz]) rotate([0, sx * 90, 0]) cylinder(d = 3.6, h = PD_SOCK_L, $fn = 24);
                translate([sx * (xe + PD_SOCK_L / 2), (PD_WIRE_Y - 1.8) / 2, PD_SOCK_Z]) cube([PD_SOCK_L, -PD_WIRE_Y + 1.8, 4.8], center = true);
            }
        }
        for (sx = [-1, 1]) {
            translate([sx * (xe + PD_SOCK_L + 0.01), 0, PD_SOCK_Z]) rotate([0, -sx * 90, 0]) {
                cylinder(d = 6.2, h = PD_SOCK_L - 1.0, $fn = 40);                                   // tube socket
                translate([0, 0, PD_SOCK_L - 1.01]) cylinder(d = GL_BORE, h = 1.02, $fn = 24);    // O-ring seat
                cylinder(d = CABLE_D + 0.1, h = PD_SOCK_L + PD_W + 2, $fn = 20);                 // cable into the box
            }
            translate([sx * (xe + PD_SOCK_L + 1), PD_WIRE_Y, PD_SOCK_Z]) rotate([0, -sx * 90, 0]) cylinder(d = NECK_D + 0.2, h = PD_SOCK_L - 0.5, $fn = 16);
            translate([sx * (xe + 1.8), PD_WIRE_Y, PD_SOCK_Z - 5]) cylinder(d = NECK_D + 0.2, h = 10, $fn = 16);   // tail hole
        }
        for (s = PD_SCR) translate([pd_scr(s)[0], pd_scr(s)[1], o[2] - 6.5]) cylinder(d = 1.6, h = 7, $fn = 16);
    }
}
module pd_seal() { difference() { pd_outline(); difference() { pd_outline(-PD_SEAL);
    for (s = PD_SCR) translate(pd_scr(s)) circle(d = PD_BOSS, $fn = 24); } } }
module pod_gasket() {   // TPU, 0.8 mm, squeezed ~25 % by the lid; seals the rim and round each screw
    translate([0, 0, pd_out()[2]]) linear_extrude(PD_GK) difference() { pd_seal(); for (s = PD_SCR) translate(pd_scr(s)) circle(d = 2.4, $fn = 16); }
}
module pod_lid() {
    c = pd_cav(); o = pd_out();
    translate([0, 0, o[2] + PD_GK]) difference() {
        union() {
            linear_extrude(PD_LID) pd_outline();
            translate([0, 0, PD_LID - 0.01]) linear_extrude(PD_RIM[1]) difference() { pd_outline(); pd_outline(-PD_RIM[0]); }   // stiff edge over the gasket
            for (y = [-6, 6]) translate([-c[0] / 2 + PD_BOSS + 1, y - 0.6, -0.8]) cube([c[0] - 2 * PD_BOSS - 2, 1.2, 0.81]);   // ribs
        }
        for (s = PD_SCR) translate([pd_scr(s)[0], pd_scr(s)[1], -2]) cylinder(d = 2.3, h = 5, $fn = 16);
        translate([0, 0, PD_LID - 0.4]) linear_extrude(0.41) text("UMEH", size = 7, halign = "center", valign = "center", font = "Liberation Sans:style=Bold");
    }
}
module pd_lipshape() { difference() { square([pd_cav()[0], pd_cav()[1]], center = true); for (s = PD_SCR) translate(pd_scr(s)) circle(d = PD_BOSS + 1.6, $fn = 24); } }
module pod_cell() { translate([-POD[0] / 2, -POD[1] / 2, PD_FL + 0.05]) cube([POD[0], POD[1], POD[2]]); }
module pod_pad() { intersection() { translate([0, 0, -30]) linear_extrude(40) offset(delta = -2) pd_outline(); difference() { pd_neck_cyl(PD_RB - 0.01); pd_neck_cyl(PD_RN); } } }
module pod_orings() { for (sx = [-1, 1]) translate([sx * (pd_out()[0] / 2 + 0.5), 0, PD_SOCK_Z]) rotate([0, 90, 0]) torus(CABLE_D / 2 + GL_CORD / 2, GL_CORD); }
if (POD != undef) {
    if (part == "pod_base") pod_base();
    if (part == "pod_lid") pod_lid();
    if (part == "pod_gasket") pod_gasket();
    if (part == "pod_cell") pod_cell();
    if (part == "pod_pad") pod_pad();
    if (part == "pod_orings") pod_orings();
    if (part == "pod_echo") echo(POD_FRAME = [pd_out()[0] / 2 + PD_SOCK_L, PD_SOCK_Z, pd_out(), pd_zf(pd_out()[0] / 2)]);
    if (part == "print_pod_base") rotate([90, 0, 0]) translate([0, pd_out()[1] / 2, 0]) pod_base();   // on its long side
    if (part == "print_pod_lid") translate([0, 0, PD_LID + PD_RIM[1] + pd_out()[2] + PD_GK]) rotate([180, 0, 0]) pod_lid();
    if (part == "print_pod_gasket") translate([0, 0, -pd_out()[2]]) pod_gasket();
    if (part == "print_neoprene_template") linear_extrude(0.6) difference() { offset(delta = -2) pd_outline();   // cutting template:
        offset(delta = -3) offset(delta = -2) pd_outline(); }                                                     // a frame to trace on the sheet
}
