// UMEH-3W: waterproof (IPX7) Bluetooth build of UMEH-3 model A. Same modules; numbers from params3w.scad
// (generated by calc/umeh3/geom.py with geom.apply("AW")), which override the UMEH-3 numbers.
include <umeh3.scad>
include <params3w.scad>
