# Study (2026-10-04): free (unloaded) shape of the neckband wire, for the printed bending/checking board.
# Worn shape = the planar path of the band calc (neckband.path -> linkspring.geometry_path: eye, straight back along the
# cup's back channel, inward over the cup edge, circular arc around the nape), with the two corners filleted (r 8 mm,
# the cup's rounded edge). Worn, each eye is pushed out by the head with P = 2 N along the eye-eye line, so the bending
# moment at a point is P * (its distance from that line). Free curvature = worn curvature + M / EI (the band closes
# when taken off). Integrated from the apex (symmetry). Writes cad/params_jig.scad (BAND_FREE, half from apex to eye).
import sys, os, math, json
import numpy as np
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from umeh3 import geom, neckband as nb, RESULTS
from umeh2.materials import WIRE
geom.apply(os.environ.get("UMEH_VAR", "AF"))
P = 2.0
d = geom.NECK_WIRE_D * 1e-3
EI = WIRE["E"].v * math.pi * d ** 4 / 64
pth = nb.path(nb.eye_point())
ex, hy, sx, ap = [pth[k] * 1e3 for k in ("eye_x", "hook_y", "side_x", "apex")]
R = (sx ** 2 + ap ** 2) / (2 * ap); cy = hy - ap + R
RF = 8.0


def worn_half(ds=0.25):
    """Points from the apex to the eye (mm), y = 0 is the eye-eye line."""
    pts = []
    th_end = math.atan2(hy - cy, sx)                    # arc end angle at (sx, hy)
    th0 = -math.pi / 2
    for t in np.arange(th0, th_end, ds / R):
        pts.append((R * math.cos(t), cy + R * math.sin(t)))
    pts.append((sx, hy))
    poly = [(sx, hy), (ex, hy), (ex, 0.0)]
    P0 = np.array(pts)
    # fillet the two polyline corners (and the arc-to-line joint is tangent already)
    out = list(P0[:-1])
    seq = [np.array(pts[-1])] + [np.array(p) for p in poly[1:]]
    for i in range(1, len(seq) - 1):
        a, b, c = seq[i - 1], seq[i], seq[i + 1]
        u = (a - b) / np.linalg.norm(a - b); v = (c - b) / np.linalg.norm(c - b)
        half = math.acos(np.clip(u @ v, -1, 1)) / 2
        t = RF / math.tan(half)
        p1, p2 = b + u * t, b + v * t
        start = out[-1] if out else a
        for s in np.arange(0, np.linalg.norm(p1 - start), ds)[1:]:
            out.append(start + (p1 - start) * s / np.linalg.norm(p1 - start))
        cen = b + (u + v) / np.linalg.norm(u + v) * RF / math.sin(half)
        a1 = math.atan2(*(p1 - cen)[::-1]); a2 = math.atan2(*(p2 - cen)[::-1])
        da = (a2 - a1 + math.pi) % (2 * math.pi) - math.pi
        for k in np.linspace(0, 1, max(3, int(abs(da) * RF / ds)))[1:]:
            ang = a1 + da * k; out.append(cen + RF * np.array([math.cos(ang), math.sin(ang)]))
    end = seq[-1]; start = out[-1]
    for s in np.arange(0, np.linalg.norm(end - start), ds)[1:]:
        out.append(start + (end - start) * s / np.linalg.norm(end - start))
    out.append(end)
    return np.array(out)


W = worn_half()
seg = np.diff(W, axis=0); L = np.linalg.norm(seg, axis=1)
ang = np.unwrap(np.arctan2(seg[:, 1], seg[:, 0]))
kap_w = np.diff(ang) / ((L[1:] + L[:-1]) / 2)          # 1/mm, at interior points
mid_y = W[1:-1, 1]
kap_f = kap_w + np.sign(np.median(kap_w)) * P * np.abs(mid_y) * 1e-3 / EI * 1e-3   # M/EI in 1/m -> 1/mm
# integrate the free shape from the apex: same start point and tangent
F = [W[0], W[1]]
a = ang[0]
for i, k in enumerate(kap_f):
    a += k * (L[i] + L[i + 1]) / 2
    F.append(F[-1] + L[i + 1] * np.array([math.cos(a), math.sin(a)]))
F = np.array(F)
F[:, 1] -= F[-1, 1]                                    # free eye-eye line at y = 0 again
res = dict(worn_eye_x=float(W[-1, 0]), free_eye_x=float(F[-1, 0]), calc_free_half_gap_mm=nb.design(P)["free_half_gap"] * 1e3,
           length_half_mm=float(L.sum()), worn_apex_y=float(W[0, 1]), free_apex_y=float(F[0, 1]),
           k_side_check_N_per_mm=P / (W[-1, 0] - F[-1, 0]))
print(json.dumps(res, indent=1))
json.dump(res, open(os.path.join(RESULTS, "band_free_shape.json" if geom.VARIANT == "AF" else f"band_free_shape_{geom.VARIANT}.json"), "w"), indent=1)
step = max(1, int(4.0 / 0.25))
pts = F[::step].tolist() + [F[-1].tolist()]
with open(os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))), "cad", "params_jig.scad"), "w") as fh:
    fh.write("// generated by calc/studies/band_free_shape.py: free shape of the neckband wire, half from the apex (x = 0) to the eye\n")
    fh.write(f"BAND_FREE = [{', '.join(f'[{p[0]:.2f}, {p[1]:.2f}]' for p in pts)}];\n")
    fh.write(f"BAND_WORN_EYE_X = {W[-1, 0]:.2f}; BAND_PIN = {geom.NECK_PIN};\n")
